/* ================================================================
   공용 메일 데이터 (Gmail / Outlook 데모 공용)
   - scenarios: 업종/직무별 실제 업무 메일 (본문 알차게 · 일부 Re:/Re:Re: 스레드)
   - NOISE: 여러 곳에서 온 광고·뉴스레터·세미나·시스템 알림
   window.DEMO = { P, scenarios, NOISE }
   ================================================================ */
(function(){
const P=["#2e8bda","#d9534f","#c77d1a","#8e44ad","#1f9d77","#c2417f","#2b7a78","#b9770e","#3a78c2","#6b7280"];
const SIG=(n,d)=>`\n\n――――――――――\n${n}｜${d}`;
const SIGe=(n,d)=>`\n\n――――――――――\n${n} | ${d}`;

const scenarios=[
 {key:"IT·개발", q:{ja:"リリース",en:"release"}, mails:[
  {f:{ja:"佐藤 健",en:"Ken Sato"},c:P[0],g:"today",t:"16:42",u:false,
   s:{ja:"本番リリース手順書を共有します",en:"Sharing the production release runbook"},
   p:{ja:"認証まわりの変更を手順書に反映しました。デプロイ前にご確認ください。",en:"Auth changes are reflected in the runbook. Please review before deploy."},
   b:{ja:"お疲れさまです、佐藤です。\n\n本日18時の本番リリースに向けて、手順書を共有フォルダ（/release/v2.4.0）にアップしました。\n今回の変更は認証まわりが中心で、影響範囲と切り戻し手順を手順書の3〜5番に追記しています。\n特にセッション有効期限の設定値が変わっているため、リリース後にログイン周りの動作を重点的に確認したいです。\n\nお手数ですが、デプロイ前に一度目を通していただけますでしょうか。気になる点があればこのスレッドで返信ください。"+SIG("佐藤 健","開発チーム / バックエンド"),
      en:"Hi team, this is Sato.\n\nAhead of today's 6 PM production release, I've uploaded the runbook to the shared folder (/release/v2.4.0).\nThis release centers on authentication; I've added the impact scope and rollback steps to sections 3–5.\nThe session-expiry value has changed, so after release let's focus on verifying the login flow.\n\nCould you look it over before the deploy? Reply on this thread with any concerns."+SIGe("Ken Sato","Dev Team / Backend")}},
  {f:{ja:"CI/CD 通知",en:"CI/CD Bot"},c:P[4],g:"today",t:"16:20",u:true,
   s:{ja:"【自動通知】デプロイ完了 (staging / v2.4.0)",en:"[Auto] Deploy completed (staging / v2.4.0)"},
   p:{ja:"ビルド #482 が正常に完了しました。テスト 312 件すべて成功。",en:"Build #482 succeeded. All 312 tests passed."},
   b:{ja:"パイプライン実行結果のお知らせです。\n\n● ブランチ: release/v2.4.0\n● ビルド番号: #482\n● 単体テスト: 312 件 成功 / 0 件 失敗\n● カバレッジ: 87.3%（前回比 +0.4pt）\n● 所要時間: 6 分 12 秒\n\nステージング環境へのデプロイが完了しました。本番反映は承認待ちです。ダッシュボードから内容をご確認ください。\nhttps://ci.example.com/pipelines/482",
      en:"Pipeline run summary.\n\n● Branch: release/v2.4.0\n● Build: #482\n● Unit tests: 312 passed / 0 failed\n● Coverage: 87.3% (+0.4pt)\n● Duration: 6m 12s\n\nDeployment to staging is complete. Production promotion is awaiting approval. Review details on the dashboard.\nhttps://ci.example.com/pipelines/482"}},
  {f:{ja:"田中 誠",en:"Makoto Tanaka"},c:P[1],g:"today",t:"15:55",u:false,
   s:{ja:"Re: コードレビュー依頼 (PR #128)",en:"Re: Code review request (PR #128)"},
   b:{ja:"佐藤さん\n\nPR #128、レビューしました。全体的に良い実装だと思います。\n2点だけコメントを残しています。\n・auth_service.js の例外処理で、リトライ上限を定数化した方が保守しやすいです\n・テストにタイムアウト系のケースを1つ追加してもらえると安心です\n\n上記対応いただければ approve します。よろしくお願いします。\n\n> 佐藤さん:\n> PR #128 のレビューをお願いできますか。優先度は中です。"+SIG("田中 誠","開発チーム / フロントエンド"),
      en:"Hi Sato,\n\nReviewed PR #128 — solid work overall. Just two comments:\n・In auth_service.js, extracting the retry limit into a constant would be easier to maintain.\n・Adding one timeout test case would give us more confidence.\n\nOnce those are addressed I'll approve. Thanks!\n\n> Sato wrote:\n> Could you review PR #128? Priority is medium."+SIGe("Makoto Tanaka","Dev Team / Frontend")}},
  {f:{ja:"高橋 由美",en:"Yumi Takahashi"},c:P[3],g:"yest",t:"18:10",u:false,
   s:{ja:"週次MTGの議事録（6/23）",en:"Weekly meeting notes (Jun 23)"},
   p:{ja:"本日の定例の議事録です。次回までのタスクをご確認ください。",en:"Today's meeting notes. Please check action items for next time."},
   b:{ja:"お疲れさまです。本日の週次MTGの議事録を共有します。\n\n【決定事項】\n・v2.4.0 は6/24 18時にリリース\n・監視アラートのしきい値を見直し（レイテンシ 800ms→500ms）\n\n【ToDo（担当 / 期限）】\n・リリース手順書の最終確認：佐藤 / 6/24 午前\n・負荷試験レポート：中村 / 6/26\n・ドキュメント更新：全員 / 随時\n\n次回は6/30(月)10:00〜です。ご確認よろしくお願いします。"+SIG("高橋 由美","開発チーム / PM"),
      en:"Sharing today's weekly meeting notes.\n\n[Decisions]\n・v2.4.0 releases Jun 24, 6 PM\n・Revised monitoring threshold (latency 800ms→500ms)\n\n[To-dos (owner / due)]\n・Final runbook check: Sato / Jun 24 AM\n・Load-test report: Nakamura / Jun 26\n・Docs update: everyone / ongoing\n\nNext meeting Mon Jun 30, 10:00. Thanks for checking."+SIGe("Yumi Takahashi","Dev Team / PM")}},
  {f:{ja:"GitHub",en:"GitHub"},c:P[9],g:"yest",t:"14:02",u:false,
   s:{ja:"[GitHub] 依存関係のセキュリティアラート (1件)",en:"[GitHub] Dependency security alert (1)"},
   p:{ja:"リポジトリで1件の脆弱性 (moderate) が検出されました。",en:"1 vulnerability (moderate) found in your repository."},
   b:{ja:"Dependabot がリポジトリ acme/web-app で脆弱性を検出しました。\n\n● パッケージ: lodash 4.17.19\n● 深刻度: Moderate (CVE-2021-23337)\n● 修正バージョン: 4.17.21\n● 対象: package-lock.json\n\n推奨対応: 依存関係を 4.17.21 以上に更新してください。自動修正 PR を作成できます。\nセキュリティタブから詳細を確認してください。",
      en:"Dependabot found a vulnerability in acme/web-app.\n\n● Package: lodash 4.17.19\n● Severity: Moderate (CVE-2021-23337)\n● Patched version: 4.17.21\n● File: package-lock.json\n\nRecommended: bump the dependency to ≥ 4.17.21. We can open an automated fix PR.\nSee the Security tab for details."}},
  {f:{ja:"中村 拓也",en:"Takuya Nakamura"},c:P[2],g:"yest",t:"11:30",u:false,
   s:{ja:"Re:Re: 新機能の仕様について",en:"Re:Re: About the new feature spec"},
   b:{ja:"佐藤さん、ご回答ありがとうございます。\n\n認識合いました。ではエクスポート形式は CSV と JSON の2種対応で進めます。\n1点だけ、大量データ時のページング仕様は別途相談させてください（1万件超のケース）。\n仕様書は明日中に更新して再共有します。\n\n> 佐藤さん:\n> エクスポートは CSV 優先で問題ありません。JSON は次フェーズでも可。\n>> 中村さん:\n>> 新機能の仕様について確認したい点が2つあります。"+SIG("中村 拓也","開発チーム / データ基盤"),
      en:"Thanks for the reply, Sato.\n\nWe're aligned. I'll proceed supporting both CSV and JSON export.\nOne thing — let me consult you separately on paging for large datasets (over 10k rows).\nI'll update the spec by tomorrow and reshare.\n\n> Sato wrote:\n> CSV first is fine. JSON can wait for the next phase.\n>> Nakamura wrote:\n>> I have two points to confirm on the new feature spec."+SIGe("Takuya Nakamura","Dev Team / Data")}},
  {f:{ja:"鈴木 一郎",en:"Ichiro Suzuki"},c:P[8],g:"today",t:"17:01",u:true,in:true,
   s:{ja:"Re:Re: 本番リリースの最終確認",en:"Re:Re: Final check before release"},
   p:{ja:"18時デプロイ前の最終確認をお願いします。問題なければ進めます。",en:"Final check before the 6 PM deploy. We'll proceed if all good."},
   b:{ja:"佐藤さん、直前のご連絡失礼します。\n\n18時のデプロイ前に、最終確認をお願いできますか。\nこちらでチェックリストは埋め終わっています（バックアップ取得済み・ロールバック手順確認済み・関係者へ周知済み）。\n残るは本番反映の承認だけです。問題なければ予定通り進めますので、OKのスタンプだけいただければと。\n\n> 高橋さん:\n> 承認フローは佐藤さんの確認後でお願いします。"+SIG("鈴木 一郎","開発チーム / SRE"),
      en:"Sato, sorry for the last-minute note.\n\nCould you do the final check before the 6 PM deploy?\nOur checklist is complete (backup taken, rollback verified, stakeholders notified).\nAll that remains is the production promotion approval. If everything's fine, we'll go as planned — just give me the OK.\n\n> Takahashi wrote:\n> Please route approval after Sato's check."+SIGe("Ichiro Suzuki","Dev Team / SRE")}},
  {f:{ja:"監視システム",en:"Monitoring"},c:P[1],g:"today",t:"17:05",u:true,in:true,
   s:{ja:"⚠【監視】APIレスポンス遅延を検知",en:"⚠ [Alert] API latency detected"},
   p:{ja:"一部エンドポイントで p95 レイテンシがしきい値を超過しています。",en:"p95 latency exceeded the threshold on some endpoints."},
   b:{ja:"監視アラート（重要度: 警告）\n\n● 対象: /api/v2/orders, /api/v2/search\n● p95 レイテンシ: 640ms（しきい値 500ms）\n● 継続時間: 直近8分\n● エラー率: 0.2%（正常範囲）\n\nリリース作業と時間帯が重なっています。デプロイ前であれば一時的な負荷の可能性もあります。\nダッシュボードで推移をご確認ください。5分以内に回復しない場合は自動で再通知します。",
      en:"Monitoring alert (severity: warning)\n\n● Targets: /api/v2/orders, /api/v2/search\n● p95 latency: 640ms (threshold 500ms)\n● Duration: last 8 min\n● Error rate: 0.2% (normal)\n\nThis overlaps with the release window; if pre-deploy, it may be transient load.\nCheck the trend on the dashboard. We'll re-alert automatically if it doesn't recover within 5 minutes."}},
 ]},

 {key:"외식·매장", q:{ja:"予約",en:"reservation"}, mails:[
  {f:{ja:"田中 美咲",en:"Misaki Tanaka"},c:P[1],g:"today",t:"16:30",u:false,
   s:{ja:"本日のランチ予約状況（合計13件）",en:"Today's lunch reservations (13 total)"},
   p:{ja:"12時台8件・13時台5件です。ピークは12時台の見込みです。",en:"8 at noon, 5 at 1 PM. Peak likely around noon."},
   b:{ja:"お疲れさまです、田中です。\n\n本日のランチ予約は合計13件、内訳は12時台が8件・13時台が5件です。\n12時台にコース予約が2組（各4名）入っているため、キッチンの立ち上がりを早めにお願いします。\nアレルギー対応が1件（甲殻類）ありますので、該当テーブルはホールで共有します。\n\n当日追加も見込まれるので、余裕をもった仕込みでお願いします。"+SIG("田中 美咲","○○店 店長"),
      en:"Hi, this is Tanaka.\n\nToday's lunch reservations total 13 — 8 at noon, 5 at 1 PM.\nTwo course bookings (4 guests each) are at noon, so please get the kitchen going early.\nOne allergy request (shellfish); the hall team will flag that table.\n\nWalk-ins are likely, so please prep with some buffer."+SIGe("Misaki Tanaka","Store Manager")}},
  {f:{ja:"本部 販促課",en:"HQ Marketing"},c:P[0],g:"today",t:"15:40",u:true,
   s:{ja:"【広告】季節限定メニュー導入のご案内（POP同梱）",en:"[Ad] New seasonal menu rollout (POP included)"},
   p:{ja:"来週月曜から季節限定の和風パスタを提供開始します。",en:"Seasonal Japanese-style pasta launches next Monday."},
   b:{ja:"各店舗ご担当者さま\n\n来週月曜（6/30）より、季節限定「和風きのこパスタ」を全店で提供開始します。\n・想定原価率: 28%　・推奨売価: 1,180円\n・提供期間: 6/30〜8/31\n・販促物: 卓上POP／ポスターA2／SNS用画像 を本日発送\n\n初週は試食キャンペーンも実施予定です。オペレーション手順書は添付をご確認ください。\n売上への貢献を期待しています。"+SIG("本部 販促課","マーケティング本部"),
      en:"To store managers,\n\nStarting next Monday (Jun 30), the seasonal \"Japanese Mushroom Pasta\" launches chain-wide.\n・Target cost ratio: 28%　・Suggested price: ¥1,180\n・Period: Jun 30 – Aug 31\n・POP: table cards / A2 posters / SNS images shipped today\n\nA tasting campaign runs the first week. See the attached ops guide.\nWe're counting on strong sales."+SIGe("HQ Marketing","Marketing Division")}},
  {f:{ja:"仕入れ 大川商店",en:"Okawa Foods"},c:P[4],g:"today",t:"14:10",u:false,
   s:{ja:"Re: 明日の納品スケジュール変更について",en:"Re: Change to tomorrow's delivery schedule"},
   b:{ja:"いつもお世話になっております、大川商店の大川です。\n\nご連絡いただいた件、明日の食材納品を午前10時着に変更いたしました。\n鮮魚については市場の都合で一部銘柄が変更になる可能性があります（同等品でのご提案となります）。\n請求は月末締めのまま変更ありません。\n\nご不明点あればお電話ください。よろしくお願いいたします。\n\n> 店長さま:\n> 明日の納品を午前中にお願いできますか。"+SIG("大川 秀樹","大川商店 営業部"),
      en:"Thank you for your continued business — Okawa here.\n\nRegarding your request, I've moved tomorrow's delivery to a 10 AM arrival.\nFor fresh fish, some items may change due to market supply (we'll propose equivalents).\nBilling remains month-end as usual.\n\nCall us with any questions. Best regards.\n\n> Manager wrote:\n> Could you deliver tomorrow in the morning?"+SIGe("Hideki Okawa","Okawa Foods / Sales")}},
  {f:{ja:"佐藤 涼",en:"Ryo Sato"},c:P[0],g:"yest",t:"19:20",u:false,
   s:{ja:"来週のシフト希望を提出します",en:"Submitting my shift request for next week"},
   b:{ja:"店長おつかれさまです、佐藤です。\n\n来週（7/1〜7/7）のシフト希望を提出します。\n・出勤可能: 月・火・木・金・土（終日）\n・NG: 水曜（学校）／日曜午前\n・土曜はクローズまで対応可能です\n\nテスト期間は落ち着いたので、来週から通常通り入れます。調整よろしくお願いします。"+SIG("佐藤 涼","ホールスタッフ"),
      en:"Hi Manager, this is Sato.\n\nHere's my shift request for next week (Jul 1–7).\n・Available: Mon, Tue, Thu, Fri, Sat (full day)\n・Unavailable: Wed (school) / Sun morning\n・I can close on Saturday\n\nExams are over, so I'm back to normal next week. Thanks for arranging."+SIGe("Ryo Sato","Hall Staff")}},
  {f:{ja:"衛生管理センター",en:"Hygiene Center"},c:P[9],g:"yest",t:"13:00",u:false,
   s:{ja:"月次清掃チェック表の提出について（期限6/28）",en:"Monthly cleaning checklist due Jun 28"},
   p:{ja:"今月の清掃チェック表を添付します。期限までにご記入ください。",en:"Attached is this month's checklist. Please complete by the deadline."},
   b:{ja:"各店舗ご担当者さま\n\n今月の清掃・衛生チェック表を送付します。\n・冷蔵/冷凍庫の温度記録\n・グリストラップ清掃（週1）\n・害虫対策の実施状況\n・従業員の健康チェック記録\n\n記入後、6/28（土）までに本部宛にご返送ください。次回の店舗巡回は7/10を予定しています。"+SIG("衛生管理センター","品質管理部"),
      en:"To store managers,\n\nHere's this month's cleaning & hygiene checklist.\n・Fridge/freezer temperature logs\n・Grease trap cleaning (weekly)\n・Pest control status\n・Staff health-check records\n\nComplete and return to HQ by Sat Jun 28. The next store visit is scheduled for Jul 10."+SIGe("Hygiene Center","Quality Assurance")}},
  {f:{ja:"予約システム",en:"Booking System"},c:P[2],g:"yest",t:"10:15",u:false,
   s:{ja:"【自動】大人数のご予約が入りました（18名）",en:"[Auto] Large group booking received (18)"},
   b:{ja:"新規のご予約が確定しました。\n\n● 日時: 6/27(金) 19:00〜\n● 人数: 18名\n● コース: 飲み放題付き宴会コース（4,500円）\n● ご要望: 座敷希望・お子様椅子2脚・記念日ケーキ1台\n\n大人数のため、レイアウト変更とドリンク体制の確認をお願いします。前日までにコース内容の最終確認をお願いします。",
      en:"A new reservation is confirmed.\n\n● When: Fri Jun 27, 7:00 PM\n● Party: 18\n● Course: Banquet w/ free-flow drinks (¥4,500)\n● Requests: tatami room, 2 kids' chairs, 1 anniversary cake\n\nGiven the size, please rearrange the layout and check drink staffing. Confirm the course details by the day before."}},
  {f:{ja:"中村 花",en:"Hana Nakamura"},c:P[2],g:"today",t:"17:02",u:true,in:true,
   s:{ja:"本日ホールの応援を1名お願いできますか",en:"Can we get one extra on the floor today?"},
   p:{ja:"予約が増えたため、ディナーのホール応援を1名お願いします。",en:"Bookings grew — need one extra on the floor for dinner."},
   b:{ja:"店長、お疲れさまです。中村です。\n\n先ほど電話予約が3件追加になり、ディナーの着席が読みづらくなってきました。\n18〜21時の時間帯だけでも、ホールに1名応援をお願いできないでしょうか。\n田中さんが上がり時間を調整できそうと言っていました。\n\n難しければ、私が休憩を後ろ倒しにして対応します。ご判断お願いします。"+SIG("中村 花","ホールリーダー"),
      en:"Hi Manager, this is Nakamura.\n\nThree more phone reservations just came in, so dinner seating is getting hard to predict.\nCould we add one person on the floor, at least for 6–9 PM?\nTanaka said they might adjust their end time.\n\nIf it's tough, I'll push my break later to cover. Your call."+SIGe("Hana Nakamura","Hall Lead")}},
  {f:{ja:"本部 売上速報",en:"HQ Sales Flash"},c:P[0],g:"today",t:"17:06",u:true,in:true,
   s:{ja:"【速報】午前売上が目標の6割に到達",en:"[Flash] Morning sales hit 60% of target"},
   b:{ja:"本日午前の売上速報です。\n\n● 午前売上: 目標比 60%\n● 客数: 前年同曜日比 +12%\n● 客単価: 1,240円（前週比 +40円）\n\n新メニューの出数が好調です。この調子でディナーも目標達成を狙いましょう。\n各店の状況は本部ダッシュボードでリアルタイムに確認できます。",
      en:"Morning sales flash.\n\n● Morning sales: 60% of target\n● Guests: +12% vs same weekday last year\n● Avg check: ¥1,240 (+¥40 WoW)\n\nThe new menu is selling well. Let's carry the momentum into dinner and hit target.\nLive figures are on the HQ dashboard."}},
 ]},

 {key:"건설·현장", q:{ja:"資材",en:"material"}, mails:[
  {f:{ja:"鈴木 現場監督",en:"Foreman Suzuki"},c:P[8],g:"today",t:"16:25",u:false,
   s:{ja:"本日の作業予定と安全連絡",en:"Today's work plan and safety notes"},
   b:{ja:"各位\n\n本日のA棟基礎工事の作業予定を共有します。\n・午前: 配筋検査（10:00 検査員立会い）→ 型枠組立\n・午後: コンクリート打設（14:00〜、生コン2台）\n\n午後から雨予報のため、打設は前倒しで進めます。降雨時は養生シートを速やかに展開してください。\n熱中症対策として、11時と15時に一斉休憩を取ります。安全第一で参りましょう。"+SIG("鈴木 太郎","○○建設 現場監督"),
      en:"All,\n\nToday's Building A foundation plan.\n・AM: rebar inspection (10:00 with inspector) → formwork\n・PM: concrete pour (from 14:00, two mixer trucks)\n\nRain is forecast for the afternoon, so we'll pour early. Deploy curing sheets promptly if it rains.\nHeat-safety breaks at 11:00 and 15:00. Safety first."+SIGe("Taro Suzuki","Site Foreman")}},
  {f:{ja:"気象情報サービス",en:"Weather Service"},c:P[0],g:"today",t:"15:30",u:true,
   s:{ja:"【気象警戒】午後の降雨・突風にご注意",en:"[Weather] Afternoon rain & gusts warning"},
   b:{ja:"現場エリアの気象情報です。\n\n● 15時頃〜: 雨（1時間あたり最大10mm）\n● 風: 南寄り、最大瞬間風速 12m/s\n● 気温: 31℃（暑さ指数 警戒）\n\n高所作業・クレーン作業は風速に注意してください。10m/sを超える場合は作業中断の判断をお願いします。\n落雷の可能性は低いですが、急変時は速やかに退避を。",
      en:"Weather for the site area.\n\n● From ~15:00: rain (up to 10mm/h)\n● Wind: southerly, gusts to 12 m/s\n● Temp: 31°C (heat caution)\n\nWatch wind for high-elevation and crane work. Consider halting if gusts exceed 10 m/s.\nLightning risk is low, but evacuate promptly on sudden changes."}},
  {f:{ja:"資材 山口鋼業",en:"Yamaguchi Steel"},c:P[4],g:"today",t:"14:00",u:false,
   s:{ja:"Re: 資材搬入の時間確定（鉄筋 10時着）",en:"Re: Material delivery time confirmed (rebar, 10 AM)"},
   b:{ja:"お世話になっております、山口鋼業です。\n\nご依頼の異形鉄筋（D13・D16）の搬入を明日10時着で確定しました。\n・数量: D13×120本、D16×80本\n・車両: 4tユニック1台\n・荷降ろし: 現場north側ヤード\n\n道路使用許可の関係で、到着が前後する場合はドライバーから直接ご連絡します。受け入れ立会いをお願いします。\n\n> 現場監督さま:\n> 明日の鉄筋搬入、午前でお願いできますか。"+SIG("山口 誠","山口鋼業 配送課"),
      en:"Thank you for your business — Yamaguchi Steel.\n\nWe've confirmed the deformed rebar (D13/D16) delivery for 10 AM tomorrow.\n・Qty: D13×120, D16×80\n・Vehicle: one 4t crane truck\n・Unloading: north yard\n\nDue to road-use permits, arrival may shift; the driver will call directly. Please have someone receive it.\n\n> Foreman wrote:\n> Could the rebar arrive in the morning?"+SIGe("Makoto Yamaguchi","Yamaguchi Steel / Logistics")}},
  {f:{ja:"安全管理室",en:"Safety Office"},c:P[9],g:"yest",t:"08:30",u:false,
   s:{ja:"安全朝礼の記録（6/23・全員出席）",en:"Safety briefing record (Jun 23, full attendance)"},
   b:{ja:"本日の安全朝礼の記録です。\n\n・出席: 8名（全員）\n・KY活動: 「型枠転倒による挟まれ」を重点\n・本日の注意点: 足元の配筋、開口部の養生\n・体調確認: 全員良好、熱中症予防のため水分補給を徹底\n\n記録は安全書類フォルダに保管しました。ヒヤリハットがあれば当日中に報告をお願いします。"+SIG("安全管理室","○○建設"),
      en:"Today's safety briefing record.\n\n・Attendance: 8 (all)\n・Risk-prediction focus: \"crush injury from formwork tipping\"\n・Watch-outs: rebar underfoot, opening covers\n・Health check: all good; stay hydrated for heat\n\nFiled in the safety folder. Report any near-misses the same day."+SIGe("Safety Office","Construction Co.")}},
  {f:{ja:"元請 大成ハウス",en:"GC Taisei House"},c:P[2],g:"yest",t:"17:40",u:false,
   s:{ja:"Re:Re: 工程表の更新（第7版）",en:"Re:Re: Schedule update (rev. 7)"},
   b:{ja:"お世話になります、大成ハウスの林です。\n\nいただいた進捗を反映し、工程表を第7版に更新しました。\n・基礎工事: 予定通り(6/30完了見込み)\n・鉄骨建方: 7/3開始 → 7/2に前倒し可否をご確認ください\n・外部足場: 7/8\n\n天候による遅延バッファは3日確保しています。次回定例(6/26)で建方の段取りを詰めましょう。\n\n> 現場監督さま:\n> 基礎は前倒しで進んでいます。建方も早められそうです。"+SIG("林 直樹","大成ハウス 工事部"),
      en:"Hello, this is Hayashi at Taisei House.\n\nI've updated the schedule to rev. 7 reflecting your progress.\n・Foundation: on track (done ~Jun 30)\n・Steel erection: starts Jul 3 → please confirm if Jul 2 is feasible\n・Exterior scaffolding: Jul 8\n\nWe've kept a 3-day weather buffer. Let's finalize erection logistics at the Jun 26 meeting.\n\n> Foreman wrote:\n> Foundation is ahead; erection could start earlier."+SIGe("Naoki Hayashi","Taisei House / Construction")}},
  {f:{ja:"田中 作業長",en:"Tanaka (Lead)"},c:P[1],g:"yest",t:"09:10",u:false,
   s:{ja:"重機点検の報告（異常なし）",en:"Machinery inspection report (no issues)"},
   b:{ja:"お疲れさまです、田中です。\n\n始業前の重機点検を実施しました。\n・バックホウ(0.45): 油圧・ブレーキ 異常なし\n・ラフター(25t): 過負荷防止装置 作動確認OK\n・発電機: 燃料残量 8割\n\nいずれも問題ありませんでした。点検表は詰所に掲示しています。クレーン作業前に再度風速を確認します。"+SIG("田中 剛","重機オペレーター"),
      en:"Hi, this is Tanaka.\n\nCompleted the pre-start machinery inspection.\n・Backhoe (0.45): hydraulics/brakes OK\n・Rough-terrain crane (25t): overload guard works\n・Generator: fuel at 80%\n\nAll clear. The checklist is posted in the site office. I'll recheck wind speed before crane work."+SIGe("Tsuyoshi Tanaka","Machine Operator")}},
  {f:{ja:"高橋 監理",en:"Takahashi (Supervisor)"},c:P[3],g:"today",t:"17:03",u:true,in:true,
   s:{ja:"Re: 本日分の進捗写真を共有ください",en:"Re: Please share today's progress photos"},
   p:{ja:"報告書に使うので、本日の配筋・打設の写真をお願いします。",en:"Need today's rebar/pour photos for the report."},
   b:{ja:"現場監督さま、お疲れさまです。\n\n本日分の進捗写真をご共有いただけますでしょうか。\n施主向け月次報告書に使用します。特に以下が必要です。\n・配筋検査時の全景と近景（検査員立会いが分かるもの）\n・打設状況\n・打設後の出来形\n\n本日中にいただけると助かります。共有フォルダにアップでも構いません。\n\n> 現場監督さま:\n> 本日は基礎の配筋検査と打設を予定しています。"+SIG("高橋 修","施工管理"),
      en:"Hi Foreman,\n\nCould you share today's progress photos? They'll go into the monthly owner report. Specifically:\n・Wide and close shots at rebar inspection (showing the inspector)\n・Pouring in progress\n・Finished form after the pour\n\nToday would be a big help. Uploading to the shared folder is fine.\n\n> Foreman wrote:\n> Today we have rebar inspection and the pour."+SIGe("Osamu Takahashi","Construction Management")}},
  {f:{ja:"元請 大成ハウス",en:"GC Taisei House"},c:P[2],g:"today",t:"17:07",u:true,in:true,
   s:{ja:"明日の資材搬入時間の確認",en:"Confirming tomorrow's material delivery time"},
   b:{ja:"度々失礼します、大成ハウスの林です。\n\n明日の資材搬入について、午前着で問題ないか最終確認させてください。\n近隣への配慮で、大型車両の入場は9〜11時に集約したいと考えています。\n搬入路の交通誘導員は2名手配済みです。\n\nご都合が合わない場合は本日中にご連絡ください。よろしくお願いいたします。"+SIG("林 直樹","大成ハウス 工事部"),
      en:"Apologies for the repeated note — Hayashi at Taisei House.\n\nA final check: is a morning arrival OK for tomorrow's material delivery?\nOut of consideration for neighbors, we'd like to consolidate large-vehicle entry into 9–11 AM.\nTwo traffic marshals are already arranged for the access road.\n\nIf this doesn't work, please let me know today. Thank you."+SIGe("Naoki Hayashi","Taisei House / Construction")}},
 ]},

 {key:"의료·간호", q:{ja:"シフト",en:"shift"}, mails:[
  {f:{ja:"高橋 看護師",en:"Nurse Takahashi"},c:P[3],g:"today",t:"16:35",u:false,
   s:{ja:"Re: 午後シフトの変更について",en:"Re: Afternoon shift change"},
   b:{ja:"師長、お疲れさまです。高橋です。\n\nご相談の午後シフトの件、15時から入れます。\n本日の受け持ちは3階東病棟でよろしいでしょうか。\n申し送りは前任の田中さんから受ける予定です。記録は電子カルテに残しておきます。\n\n夜勤明けの佐藤さんが早めに上がれるよう、引き継ぎを優先します。\n\n> 師長:\n> 午後のシフト、15時から入れそうですか？"+SIG("高橋 綾","3E病棟 看護師"),
      en:"Hi Head Nurse, this is Takahashi.\n\nRegarding the afternoon shift, I can start at 3 PM.\nShall I take the 3F East ward today?\nI'll take handover from Tanaka and note everything in the EMR.\n\nI'll prioritize the handover so post-night-shift Sato can leave early.\n\n> Head Nurse wrote:\n> Can you start the afternoon shift at 3 PM?"+SIGe("Aya Takahashi","3E Ward Nurse")}},
  {f:{ja:"看護部",en:"Nursing Dept."},c:P[0],g:"today",t:"15:20",u:true,
   s:{ja:"来月の勤務表を更新しました（希望休反映）",en:"Next month's roster updated (days off reflected)"},
   b:{ja:"各病棟スタッフの皆さまへ\n\n来月（7月）の勤務表を更新しました。提出いただいた希望休はすべて反映しています。\n・夜勤回数は原則1人月4回まで\n・連続夜勤は2回まで\n・年次有給の申請は前月20日締め\n\n変更希望がある場合は、6/28までに各病棟の主任へお申し出ください。人員に余裕のない日は調整をお願いすることがあります。"+SIG("看護部","勤務管理担当"),
      en:"To all ward staff,\n\nThe July roster is updated, with all requested days off reflected.\n・Night shifts: max 4/month per person\n・Consecutive nights: max 2\n・Annual leave requests: due the 20th of the prior month\n\nFor change requests, tell your ward lead by Jun 28. On short-staffed days we may ask for adjustments."+SIGe("Nursing Dept.","Scheduling")}},
  {f:{ja:"薬剤部",en:"Pharmacy"},c:P[4],g:"today",t:"14:05",u:false,
   s:{ja:"305号室 点滴準備完了（16時交換予定）",en:"IV for Room 305 ready (change at 4 PM)"},
   b:{ja:"看護部各位\n\n305号室 患者様の点滴を準備しました。\n・内容: 維持輸液＋抗生剤（指示書No.4471）\n・交換予定: 本日16時\n・注意: 前回投与時に軽度の血管痛あり。滴下速度に注意してください。\n\n受け取りは薬剤部窓口までお願いします。指示変更があれば当直医に確認します。"+SIG("薬剤部","調剤担当"),
      en:"To nursing staff,\n\nThe IV for the Room 305 patient is prepared.\n・Contents: maintenance fluid + antibiotic (order No. 4471)\n・Change: today at 4 PM\n・Note: mild vascular pain last time — watch the drip rate.\n\nPlease collect it at the pharmacy window. We'll confirm with the on-call doctor for any order changes."+SIGe("Pharmacy","Dispensing")}},
  {f:{ja:"佐藤 主任",en:"Chief Sato"},c:P[0],g:"yest",t:"20:00",u:false,
   s:{ja:"301号室 患者経過の報告",en:"Room 301 patient progress report"},
   b:{ja:"お疲れさまです、佐藤です。\n\n301号室の患者様、経過は安定しています。\n・バイタル: BP 122/78、HR 72、SpO2 98%、体温 36.8℃\n・食事: 全量摂取、嘔気なし\n・疼痛: NRS 2（鎮痛剤で良好にコントロール）\n\n夜間も特記事項なく経過。明日の回診でリハビリ開始の可否を主治医に確認予定です。申し送り済みです。"+SIG("佐藤 恵","3E病棟 主任"),
      en:"Hi, this is Sato.\n\nThe Room 301 patient is stable.\n・Vitals: BP 122/78, HR 72, SpO2 98%, temp 36.8°C\n・Meals: full intake, no nausea\n・Pain: NRS 2 (well controlled with analgesics)\n\nNo issues overnight. At tomorrow's rounds I'll ask the attending about starting rehab. Handover done."+SIGe("Megumi Sato","3E Ward Chief")}},
  {f:{ja:"事務局",en:"Admin Office"},c:P[9],g:"yest",t:"12:30",u:false,
   s:{ja:"【要出席登録】来週の感染対策研修のご案内",en:"[RSVP] Infection-control training next week"},
   b:{ja:"職員各位\n\n来週、感染対策の院内研修を実施します。\n・日時: 7/2(水) 17:30〜18:30\n・場所: 3階 大会議室（オンライン参加も可）\n・内容: 手指衛生の最新ガイドライン、針刺し事故防止\n\n全職員必須です。出席登録フォームから6/30までにご登録ください。当日参加できない方向けに録画を後日共有します。"+SIG("事務局","医療安全管理室"),
      en:"To all staff,\n\nAn in-house infection-control training will be held next week.\n・When: Wed Jul 2, 5:30–6:30 PM\n・Where: 3F large conference room (online option available)\n・Topics: latest hand-hygiene guidelines, needlestick prevention\n\nMandatory for all staff. Register via the form by Jun 30. A recording will be shared for those who can't attend."+SIGe("Admin Office","Patient Safety")}},
  {f:{ja:"田中 夜勤",en:"Tanaka (Night)"},c:P[1],g:"yest",t:"07:00",u:false,
   s:{ja:"夜勤の申し送り事項",en:"Night-shift handover notes"},
   b:{ja:"日勤の皆さまへ、夜勤の申し送りです。\n\n・302号室: 23時に発熱(38.2℃)、クーリングで37.5℃まで低下。朝の再検温をお願いします。\n・308号室: 不眠訴えあり、指示範囲内で眠剤対応済み。\n・共有: 3時にナースコール集中、大きな事故なし。\n\n詳細は看護記録をご確認ください。何かあれば携帯まで。お疲れさまでした。"+SIG("田中 恵子","夜勤担当"),
      en:"To the day shift — night handover.\n\n・Room 302: fever (38.2°C) at 11 PM, down to 37.5°C with cooling. Please recheck this morning.\n・Room 308: reported insomnia; sleep aid given within orders.\n・Note: call bells spiked at 3 AM, no major incidents.\n\nSee the nursing records for details. Reach me by phone if needed. Thanks."+SIGe("Keiko Tanaka","Night Shift")}},
  {f:{ja:"中村 師長",en:"Head Nurse Nakamura"},c:P[2],g:"today",t:"17:02",u:true,in:true,
   s:{ja:"Re: 301号室 ご家族への説明のお願い",en:"Re: Please brief Room 301's family"},
   p:{ja:"本日中に301号室のご家族へ経過説明をお願いできますか。",en:"Could you brief Room 301's family on progress today?"},
   b:{ja:"高橋さん、お疲れさまです。\n\n301号室のご家族が15時頃に来院されます。経過説明をお願いできますか。\n主治医からは「状態は安定、リハビリ開始を検討」と伝えて問題ないと確認済みです。\n退院時期についてはまだ確定していない旨、丁寧にお伝えください。\n\n説明後は内容を記録に残しておいてください。よろしくお願いします。"+SIG("中村 里佳","3E病棟 師長"),
      en:"Hi Takahashi,\n\nRoom 301's family will visit around 3 PM. Could you brief them on progress?\nThe attending confirmed it's fine to say \"stable, considering starting rehab.\"\nPlease gently note that the discharge date isn't set yet.\n\nRecord the discussion afterward. Thank you."+SIGe("Rika Nakamura","3E Ward Head Nurse")}},
  {f:{ja:"当直医",en:"On-call Doctor"},c:P[1],g:"today",t:"17:06",u:true,in:true,
   s:{ja:"【指示変更】投薬指示の一部変更",en:"[Order change] Partial medication update"},
   b:{ja:"看護部各位\n\n本日付で以下の投薬指示を変更します。\n・305号室: 抗生剤を1日3回→2回に変更（朝夕）\n・301号室: 鎮痛剤は頓用のみ、定時投与は中止\n\n電子カルテの指示も更新済みです。実施前に必ず最新の指示を確認してください。\n不明点があれば内線202までご連絡ください。"+SIG("内科 山下","当直医"),
      en:"To nursing staff,\n\nEffective today, the following medication orders change:\n・Room 305: antibiotic from 3×/day → 2×/day (AM/PM)\n・Room 301: analgesic PRN only; discontinue scheduled dosing\n\nThe EMR orders are updated. Always check the latest order before administering.\nQuestions: ext. 202."+SIGe("Dr. Yamashita","On-call (Internal Medicine)")}},
 ]},

 {key:"소매·판매", q:{ja:"在庫",en:"stock"}, mails:[
  {f:{ja:"中村 フロア長",en:"Floor Lead Nakamura"},c:P[2],g:"today",t:"16:28",u:false,
   s:{ja:"新商品の入荷連絡と陳列のお願い",en:"New stock arrived — please display"},
   b:{ja:"皆さまお疲れさまです、中村です。\n\n夏物新商品が入荷しました（段ボール6箱、バックヤードA-3）。\n・Tシャツ3型（各S/M/L）\n・トートバッグ2色\n\n本日中に補充と陳列をお願いします。入口正面のマグネット什器に展開してください。\n値札はハンディで発行できます。売れ筋は早めの追加補充をお願いします。"+SIG("中村 亮","フロア長"),
      en:"Hi everyone, this is Nakamura.\n\nSummer new arrivals are in (6 boxes, backyard A-3).\n・3 T-shirt styles (S/M/L each)\n・Tote bags in 2 colors\n\nPlease restock and display today, on the front magnet fixture at the entrance.\nPrice tags can be printed on the handheld. Reorder best-sellers early."+SIGe("Ryo Nakamura","Floor Lead")}},
  {f:{ja:"本部 販促",en:"HQ Promo"},c:P[0],g:"today",t:"15:10",u:true,
   s:{ja:"【広告】本日限り 全品10%OFFセールのご案内",en:"[Ad] Today only — 10% off storewide"},
   b:{ja:"店舗各位\n\n本日、全品10%OFFのタイムセールを実施します。\n・時間: 開店〜閉店（一部除外品あり）\n・告知: 店頭ポスター、公式アプリ、SNSで配信済み\n・レジ: セール用のクーポンコードを適用してください\n\nディスプレイをセール仕様に変更し、入口に「本日限り」POPを掲出してください。売り逃しのないよう補充も徹底を。"+SIG("本部 販促課","マーケティング"),
      en:"To all stores,\n\nToday we're running a 10% off storewide flash sale.\n・Time: open to close (some exclusions)\n・Promo: in-store posters, official app, and SNS already pushed\n・Register: apply the sale coupon code\n\nSwitch displays to sale mode and post the \"Today only\" POP at the entrance. Keep shelves stocked so we don't miss sales."+SIGe("HQ Promo","Marketing")}},
  {f:{ja:"POSシステム",en:"POS System"},c:P[4],g:"today",t:"14:00",u:false,
   s:{ja:"【自動】午前の売上レポート",en:"[Auto] Morning sales report"},
   b:{ja:"本日午前（開店〜12:00）の売上レポートです。\n\n● 売上: 目標比 60%\n● 客数: 148名（前週比 +9%）\n● 客単価: 3,120円\n● レジ稼働: 2台\n● 部門別トップ: レディース > 雑貨 > メンズ\n\nセール開始後の伸びが顕著です。混雑時間帯（12〜14時）はレジ増設をご検討ください。",
      en:"Morning sales report (open–12:00).\n\n● Sales: 60% of target\n● Guests: 148 (+9% WoW)\n● Avg check: ¥3,120\n● Registers open: 2\n● Top depts: Women's > Goods > Men's\n\nGrowth is strong after the sale started. Consider adding a register for the 12–14:00 rush."}},
  {f:{ja:"佐藤 スタッフ",en:"Sato (Staff)"},c:P[0],g:"yest",t:"18:30",u:false,
   s:{ja:"人気商品の補充報告（写真あり）",en:"Restock report for best-sellers (photos)"},
   b:{ja:"フロア長お疲れさまです、佐藤です。\n\n本日の人気商品の補充が完了しました。\n・リネンシャツ(白): 残3→12に補充\n・キャンバストート: 完売のため明日入荷分を優先陳列予定\n\n売場の写真を共有フォルダに上げています。トート待ちのお客様が数名いたので、入荷後すぐ連絡できるよう取り置きメモを残しました。"+SIG("佐藤 みなみ","販売スタッフ"),
      en:"Hi Floor Lead, this is Sato.\n\nRestocking of today's best-sellers is done.\n・Linen shirt (white): 3 → 12\n・Canvas tote: sold out; I'll prioritize tomorrow's delivery on the floor\n\nI've uploaded floor photos to the shared folder. A few customers were waiting for the tote, so I left hold notes to contact them once it arrives."+SIGe("Minami Sato","Sales Staff")}},
  {f:{ja:"物流センター",en:"Logistics Center"},c:P[9],g:"yest",t:"11:20",u:false,
   s:{ja:"明日の入荷予定（午前2便）",en:"Tomorrow's deliveries (2 morning trucks)"},
   b:{ja:"店舗ご担当者さま\n\n明日の入荷予定をお知らせします。\n・第1便: 9:30着（アパレル 中心・12箱）\n・第2便: 11:00着（雑貨・8箱）\n\n検品スペースの確保と、返品予定分の引き取りをお願いします。伝票番号はシステムに登録済みです。破損があれば写真を添えて当日中にご連絡ください。"+SIG("物流センター","入出荷管理"),
      en:"To store staff,\n\nTomorrow's deliveries:\n・Truck 1: arrives 9:30 (mostly apparel, 12 boxes)\n・Truck 2: arrives 11:00 (goods, 8 boxes)\n\nPlease clear inspection space and hand over returns for pickup. Slip numbers are in the system. Report any damage the same day with photos."+SIGe("Logistics Center","Inbound/Outbound")}},
  {f:{ja:"田中  VMD",en:"Tanaka (VMD)"},c:P[1],g:"yest",t:"10:00",u:false,
   s:{ja:"ディスプレイ変更後の写真を共有します",en:"Sharing photos of the updated display"},
   b:{ja:"お疲れさまです、VMD担当の田中です。\n\n入口とセンターテーブルの什器変更が完了しました。写真を共有します。\n・入口: 夏物カラーで統一、マネキン2体に新作コーデ\n・センター: セール品を島陳列\n\n次回は7/5に秋の先行企画へ変更予定です。各店の売上データを見ながら微調整していきます。ご意見あればお寄せください。"+SIG("田中 洋平","VMD担当"),
      en:"Hi, this is Tanaka from VMD.\n\nThe entrance and center-table fixtures are updated — sharing photos.\n・Entrance: unified summer colors, two mannequins in new looks\n・Center: sale items in island display\n\nNext change is Jul 5 for the early autumn theme. We'll fine-tune using each store's sales data. Feedback welcome."+SIGe("Yohei Tanaka","VMD")}},
  {f:{ja:"本部 販促",en:"HQ Promo"},c:P[0],g:"today",t:"17:02",u:true,in:true,
   s:{ja:"Re: 夕方の増員（レジ3台）について",en:"Re: Evening staffing (third register)"},
   p:{ja:"夕方の混雑に備えてレジを3台に増やしましょう。シフト調整をお願いします。",en:"Let's open a third register for the evening rush."},
   b:{ja:"各店フロア長さま\n\nセール好調につき、夕方の混雑が予想されます。\n17〜20時はレジを3台体制に増やしてください。応援が必要な場合は近隣店と融通いただいて構いません。\nお会計待ちの列が5名を超えたら、即座に増設の判断をお願いします。\n\n本日の目標達成まであと一息です。よろしくお願いします。\n\n> 中村さん:\n> セール開始後、来店が増えています。"+SIG("本部 販促課","マーケティング"),
      en:"To floor leads,\n\nWith the sale doing well, expect an evening rush.\nRun three registers from 17:00–20:00. Borrow help from nearby stores if needed.\nOpen another register immediately if the checkout line exceeds five people.\n\nWe're almost at today's target — thanks!\n\n> Nakamura wrote:\n> Foot traffic is up since the sale started."+SIGe("HQ Promo","Marketing")}},
  {f:{ja:"顧客対応窓口",en:"Customer Service"},c:P[1],g:"today",t:"17:05",u:true,in:true,
   s:{ja:"Re: 在庫に関するお問い合わせ対応のお願い",en:"Re: Customer stock inquiry — please handle"},
   b:{ja:"店舗ご担当者さま\n\nお客様から在庫確認のお問い合わせが入っています。\n・商品: リネンシャツ(白) Mサイズ\n・内容: 「オンラインで在庫なし。店頭にあれば取り置き希望」\n・連絡先: お客様番号 C-20461（折り返し希望）\n\n店頭在庫をご確認のうえ、取り置き可否を本日中にお客様へご連絡ください。対応後、こちらの窓口にも結果を共有いただけると助かります。"+SIG("顧客対応窓口","カスタマーサポート"),
      en:"To store staff,\n\nA customer stock inquiry has come in.\n・Item: Linen shirt (white), size M\n・Details: \"Out of stock online — would like a hold if in store\"\n・Contact: customer C-20461 (requests a callback)\n\nPlease check in-store stock and let the customer know about a hold today. Share the outcome back with us afterward."+SIGe("Customer Service","Support")}},
 ]},

 {key:"제조·공장", q:{ja:"検品",en:"inspection"}, mails:[
  {f:{ja:"伊藤 ライン長",en:"Line Lead Ito"},c:P[5],g:"today",t:"16:30",u:false,
   s:{ja:"本日のライン稼働報告（目標達成見込み）",en:"Today's line status (on track)"},
   b:{ja:"お疲れさまです、伊藤です。\n\n本日の第1ラインの稼働状況を報告します。\n・計画数: 4,800個　・実績(16時時点): 3,720個\n・稼働率: 96%　・チョコ停: 2回（合計7分）\n・目標達成見込み: ○\n\n午後の材料切替もスムーズでした。残り2時間、品質を保ちながら完遂します。設備の異音等は現時点でありません。"+SIG("伊藤 健二","第1ライン 班長"),
      en:"Hi, this is Ito.\n\nLine 1 status for today.\n・Plan: 4,800 units　・Actual (as of 16:00): 3,720\n・Utilization: 96%　・Minor stops: 2 (7 min total)\n・On track to hit target: yes\n\nThe afternoon material changeover went smoothly. Two hours left — we'll finish while holding quality. No abnormal machine noise so far."+SIGe("Kenji Ito","Line 1 Lead")}},
  {f:{ja:"品質管理課",en:"QC Dept."},c:P[0],g:"today",t:"15:25",u:true,
   s:{ja:"Re: 検品結果の報告（不良率0.3%）",en:"Re: Inspection result (defect rate 0.3%)"},
   b:{ja:"各位\n\n本日午後ロットの検品結果です。\n・検査数: 1,200個　・不良: 4個（0.3%）\n・不良内訳: 外観キズ3、寸法公差外1\n・基準: 社内基準(0.5%)内、合格\n\nキズは搬送ローラーの摩耗が原因の可能性があり、保全に点検を依頼しました。是正状況は明日共有します。\n\n> ライン長:\n> 午後ロットの検品をお願いします。"+SIG("品質管理課","検査担当"),
      en:"All,\n\nInspection result for this afternoon's lot.\n・Inspected: 1,200　・Defects: 4 (0.3%)\n・Breakdown: 3 cosmetic scratches, 1 out-of-tolerance\n・Standard: within internal 0.5% — pass\n\nScratches may stem from a worn conveyor roller; I've asked maintenance to inspect. I'll share the fix status tomorrow.\n\n> Line Lead wrote:\n> Please inspect the afternoon lot."+SIGe("QC Dept.","Inspection")}},
  {f:{ja:"資材部",en:"Materials Dept."},c:P[4],g:"today",t:"14:10",u:false,
   s:{ja:"資材在庫状況の連絡（明日分まで確保）",en:"Stock status (secured through tomorrow)"},
   b:{ja:"製造各位\n\n主要資材の在庫状況をお知らせします。\n・樹脂ペレットA: 明日分まで確保（在庫2.1t）\n・箱材: 3日分\n・ラベル: 本日夕方に追加入荷予定\n\n追加発注は現時点で不要です。ラベルの入荷が遅れる場合は代替の白ラベルで対応します。週明けの生産計画に合わせ、来週分を明日発注します。"+SIG("資材部","購買担当"),
      en:"To manufacturing,\n\nKey material stock status.\n・Resin pellets A: secured through tomorrow (2.1t)\n・Box material: 3 days\n・Labels: additional delivery this evening\n\nNo extra order needed now. If labels are delayed, we'll use plain white as a substitute. We'll order next week's supply tomorrow to match the plan."+SIGe("Materials Dept.","Purchasing")}},
  {f:{ja:"設備保全",en:"Maintenance"},c:P[9],g:"yest",t:"17:00",u:false,
   s:{ja:"今週末の定期点検の予定（停止時間の確認）",en:"Scheduled maintenance this weekend (downtime)"},
   b:{ja:"関係各位\n\n今週末に第2ラインの定期点検を実施します。\n・日時: 6/28(土) 8:00〜13:00\n・内容: 主軸ベアリング交換、センサー校正、清掃\n・停止範囲: 第2ラインのみ（第1は通常稼働）\n\n点検中は該当エリア立入制限となります。土曜出荷分は金曜のうちに前倒し生産をお願いします。点検後、試運転して問題なければ月曜朝から通常稼働です。"+SIG("設備保全課","保全担当"),
      en:"To all concerned,\n\nScheduled maintenance on Line 2 this weekend.\n・When: Sat Jun 28, 8:00–13:00\n・Work: main-shaft bearing replacement, sensor calibration, cleaning\n・Downtime: Line 2 only (Line 1 runs normally)\n\nThe area is restricted during work. Please pull Saturday's shipment forward to Friday. After a test run, normal operation resumes Monday morning."+SIGe("Maintenance","Facilities")}},
  {f:{ja:"佐藤 段取り",en:"Sato (Setup)"},c:P[0],g:"yest",t:"13:40",u:false,
   s:{ja:"次ロットの段取り準備状況",en:"Next lot setup — progress"},
   b:{ja:"お疲れさまです、佐藤です。\n\n次ロット（製品コード B-220）の段取り準備を進めています。\n・金型交換: 完了\n・材料手配: 済み\n・初品検査の治具: 準備中（あと30分）\n\n準備が整い次第、試作1個を品管に回して初品承認を取ります。承認後すぐに量産へ移れる体制です。予定より15分ほど早く着手できそうです。"+SIG("佐藤 大輔","段取り担当"),
      en:"Hi, this is Sato.\n\nSetting up the next lot (product B-220).\n・Die change: done\n・Material: arranged\n・First-article jig: in prep (about 30 min)\n\nOnce ready, I'll send a first article to QC for approval, then move straight into mass production. We can start about 15 minutes ahead of schedule."+SIGe("Daisuke Sato","Setup")}},
  {f:{ja:"生産管理",en:"Production Planning"},c:P[2],g:"yest",t:"09:50",u:false,
   s:{ja:"来週の生産計画を更新しました",en:"Next week's production plan updated"},
   b:{ja:"各ライン責任者へ\n\n来週(7/1週)の生産計画を更新しました。\n・第1ライン: B-220 を優先（受注増のため+15%）\n・第2ライン: 土曜点検のため金曜に前倒し\n・人員: 中番を1名増員\n\n各ラインへの展開と、材料・治具の事前準備をお願いします。計画変更の詳細はシステムの生産オーダーをご確認ください。"+SIG("生産管理課","計画担当"),
      en:"To line managers,\n\nNext week's (Jul 1) production plan is updated.\n・Line 1: prioritize B-220 (+15% on higher orders)\n・Line 2: pull forward to Friday due to Saturday maintenance\n・Staffing: +1 on middle shift\n\nPlease roll this out and pre-stage materials and jigs. See the production orders in the system for details."+SIGe("Production Planning","Scheduling")}},
  {f:{ja:"高橋 保全",en:"Takahashi (Maint.)"},c:P[3],g:"today",t:"17:03",u:true,in:true,
   s:{ja:"Re: 第2ラインの温度確認のお願い",en:"Re: Please check Line 2 temperature"},
   p:{ja:"念のため第2ラインの成形温度を確認いただけますか。",en:"Could you check Line 2's molding temperature, just in case?"},
   b:{ja:"伊藤さん、お疲れさまです。\n\n先ほどの検品でキズ不良が出た件、搬送系だけでなく成形温度の影響も切り分けたいです。\n第2ラインの成形温度（設定 210℃）が安定しているか、直近1時間のトレンドを確認いただけますか。\n±3℃を超える変動があれば、ヒーターの制御を点検します。\n\nお手すきで構いませんので、結果を教えてください。"+SIG("高橋 淳","設備保全課"),
      en:"Hi Ito,\n\nOn the scratch defects from the last inspection, I want to rule out molding temperature, not just the conveyor.\nCould you check whether Line 2's molding temp (set 210°C) is stable over the last hour?\nIf it swings more than ±3°C, I'll inspect the heater control.\n\nNo rush — just let me know the result."+SIGe("Jun Takahashi","Maintenance")}},
  {f:{ja:"品質管理課",en:"QC Dept."},c:P[0],g:"today",t:"17:06",u:true,in:true,
   s:{ja:"出荷前チェックの結果（問題なし）",en:"Pre-shipment check result (no issues)"},
   b:{ja:"出荷担当各位\n\n本日出荷分の最終チェックが完了しました。\n・対象: B-210 ×1,000個（3パレット）\n・外観・寸法・梱包表示: いずれも合格\n・出荷書類: 検査成績書を添付\n\n問題ありませんので、予定通り明日午前の便で出荷可能です。トレーサビリティ用のロット記録も保存済みです。"+SIG("品質管理課","出荷検査"),
      en:"To shipping staff,\n\nFinal check for today's shipment is complete.\n・Items: B-210 ×1,000 (3 pallets)\n・Appearance/dimensions/labeling: all pass\n・Docs: inspection certificate attached\n\nNo issues — ready to ship on tomorrow's morning truck as planned. Lot records for traceability are saved."+SIGe("QC Dept.","Shipping Inspection")}},
 ]},

 {key:"물류·배송", q:{ja:"ルート",en:"route"}, mails:[
  {f:{ja:"渡辺 配車",en:"Watanabe (Dispatch)"},c:P[6],g:"today",t:"16:20",u:false,
   s:{ja:"本日の配送ルート確定（午前10・午後8）",en:"Today's routes confirmed (10 AM / 8 PM)"},
   b:{ja:"ドライバー各位、お疲れさまです。\n\n本日の配送ルートを確定しました。\n・午前: 10件（市内中心部、9:00出発）\n・午後: 8件（郊外、13:00出発）\n・時間指定: 午前3件（うち2件は午前必着）\n\n端末に最新ルートを配信済みです。時間指定分を優先し、無理のない範囲で回してください。到着遅れが見込まれる場合は早めに連絡を。"+SIG("渡辺 大輔","配車センター"),
      en:"To all drivers,\n\nToday's routes are confirmed.\n・AM: 10 stops (downtown, depart 9:00)\n・PM: 8 stops (suburbs, depart 13:00)\n・Time-slots: 3 in the morning (2 must arrive AM)\n\nThe latest route is pushed to your device. Prioritize time-slot stops and drive safely. Call early if delays are likely."+SIGe("Daisuke Watanabe","Dispatch Center")}},
  {f:{ja:"配車システム",en:"Dispatch System"},c:P[0],g:"today",t:"15:30",u:true,
   s:{ja:"【自動】再配達の依頼が2件入りました",en:"[Auto] 2 redelivery requests received"},
   b:{ja:"再配達の依頼が届きました。\n\n【1件目】伝票 4471-88　時間帯: 18-20時　地区: 東5丁目\n【2件目】伝票 4471-92　時間帯: 19-21時　地区: 西2丁目\n\nいずれも本日中の希望です。午後便のルートに組み込んでください。ご不在票の記載と相違ないか、配達時にご確認をお願いします。",
      en:"Redelivery requests received.\n\n[1] Slip 4471-88　Window: 18:00–20:00　Area: East 5\n[2] Slip 4471-92　Window: 19:00–21:00　Area: West 2\n\nBoth requested for today. Please fold them into the afternoon route. Verify against the absence notice at delivery."}},
  {f:{ja:"倉庫 出荷",en:"Warehouse"},c:P[4],g:"today",t:"14:05",u:false,
   s:{ja:"冷蔵品の積み込み完了（温度確認済み）",en:"Refrigerated cargo loaded (temp verified)"},
   b:{ja:"配送担当各位\n\n午後便の冷蔵品の積み込みが完了しました。\n・品目: 冷蔵食品 24ケース\n・庫内温度: 4.2℃（規定 0〜5℃内）\n・保冷剤: 追加投入済み\n\n温度記録シートは車載しています。配達先での引き渡し時に、受領サインと温度確認欄への記入をお願いします。ドアの開閉は最小限でお願いします。"+SIG("倉庫 出荷課","品質保持担当"),
      en:"To delivery staff,\n\nThe afternoon refrigerated cargo is loaded.\n・Items: 24 cases of chilled food\n・Interior temp: 4.2°C (within 0–5°C)\n・Ice packs: added\n\nThe temp-log sheet is in the vehicle. At handover, please get the receiver's signature and fill the temperature field. Minimize door openings."+SIGe("Warehouse","Cold Chain")}},
  {f:{ja:"佐藤 点検",en:"Sato (Check)"},c:P[0],g:"yest",t:"07:30",u:false,
   s:{ja:"出発前の車両点検報告（異常なし）",en:"Pre-departure vehicle check (no issues)"},
   b:{ja:"お疲れさまです、佐藤です。\n\n本日の担当車両（車番 品川88-12）の出発前点検を実施しました。\n・タイヤ空気圧・溝: 良好\n・ブレーキ・灯火類: 正常\n・冷蔵ユニット: 設定4℃で稼働確認\n・燃料: 満タン\n\nアルコールチェックも実施済み、数値0.00。問題ありませんので予定通り出発します。"+SIG("佐藤 隆","配送ドライバー"),
      en:"Hi, this is Sato.\n\nCompleted the pre-departure check on my vehicle (plate 88-12).\n・Tire pressure/tread: good\n・Brakes/lights: normal\n・Refrigeration unit: running at 4°C\n・Fuel: full\n\nAlcohol check done, reading 0.00. No issues — departing as planned."+SIGe("Takashi Sato","Delivery Driver")}},
  {f:{ja:"交通情報",en:"Traffic Info"},c:P[9],g:"yest",t:"16:40",u:false,
   s:{ja:"【注意】環状線で渋滞発生・迂回のご検討を",en:"[Notice] Congestion on loop line — consider detour"},
   b:{ja:"配送関係各位\n\n環状3号線（東IC〜中央JCT）で事故渋滞が発生しています。\n・渋滞長: 約4km　・通過所要: 通常+25分\n・復旧見込み: 18時頃\n\n該当区間を通るルートは、県道12号への迂回をご検討ください。ナビの再探索も推奨します。時間指定便は遅延の可能性があるため、必要に応じてお客様へ事前連絡をお願いします。"+SIG("交通情報センター","運行管理"),
      en:"To delivery staff,\n\nAccident congestion on Loop Route 3 (East IC–Central JCT).\n・Length: ~4km　・Delay: +25 min vs normal\n・Clearing: around 18:00\n\nFor routes through this section, consider detouring via Route 12. Re-route your nav. Time-slot deliveries may be delayed — contact customers in advance as needed."+SIGe("Traffic Center","Operations")}},
  {f:{ja:"田中 運行",en:"Tanaka (Ops)"},c:P[1],g:"yest",t:"09:00",u:false,
   s:{ja:"到着予定はアプリで随時更新します",en:"ETAs will be updated in the app"},
   b:{ja:"お客様・関係各位\n\n本日より、各便の到着予定時刻を配送アプリでリアルタイム更新します。\n・確認方法: アプリの「配送状況」からリンクで地図表示\n・更新間隔: 5分ごと\n・通知: 到着30分前にプッシュ通知\n\nこれまでの電話確認が不要になります。ご不明な点はサポート窓口までお願いします。ご活用ください。"+SIG("田中 健","運行管理課"),
      en:"To customers and staff,\n\nStarting today, each delivery's ETA updates in real time in the app.\n・How: \"Delivery status\" → map view via link\n・Interval: every 5 min\n・Alerts: push notification 30 min before arrival\n\nThis removes the need for phone confirmations. Contact support with any questions. Please make use of it."+SIGe("Ken Tanaka","Operations")}},
  {f:{ja:"中村 集荷",en:"Nakamura (Pickup)"},c:P[2],g:"today",t:"17:02",u:true,in:true,
   s:{ja:"Re: 午後の追加集荷が1件入りました",en:"Re: One extra pickup this afternoon"},
   p:{ja:"午後に追加集荷が1件入りました。対応可能でしょうか。",en:"An extra pickup came in for this afternoon. Can you take it?"},
   b:{ja:"渡辺さん、お疲れさまです。\n\n午後に法人のお客様から追加集荷の依頼が入りました。\n・集荷先: 中央区の○○商事\n・時間: 15〜16時希望\n・個数: 12個（うち割れ物3）\n\n西2丁目の再配達ルートと近いので、そこに組み込めないでしょうか。難しければ夕方便の担当を1名回します。ご判断お願いします。"+SIG("中村 誠","集荷担当"),
      en:"Hi Watanabe,\n\nA corporate customer requested an extra pickup this afternoon.\n・From: ABC Trading, Chuo Ward\n・Time: prefers 15:00–16:00\n・Pieces: 12 (3 fragile)\n\nIt's near the West 2 redelivery route — could we fold it in there? If not, I'll assign one driver from the evening run. Your call."+SIGe("Makoto Nakamura","Pickup")}},
  {f:{ja:"配車システム",en:"Dispatch System"},c:P[0],g:"today",t:"17:05",u:true,in:true,
   s:{ja:"【提案】本日ルートの最適化（約20分短縮）",en:"[Suggestion] Route optimization (~20 min saved)"},
   b:{ja:"ルート最適化のご提案です。\n\n現在の午後ルート（8件）を再計算した結果、訪問順の入れ替えで走行距離を約7km、所要を約20分短縮できます。\n・変更点: 4番目と6番目の訪問順を入れ替え\n・渋滞回避: 環状線を避け県道12号を通過\n・時間指定への影響: なし\n\n適用する場合はアプリの「最適化を反映」を押してください。反映後、端末に新ルートが配信されます。",
      en:"A route optimization suggestion.\n\nRecomputing the current afternoon route (8 stops), reordering visits cuts ~7km and ~20 minutes.\n・Change: swap the 4th and 6th stops\n・Avoids congestion: uses Route 12 instead of the loop\n・Impact on time-slots: none\n\nTo apply, tap \"Apply optimization\" in the app. The new route is then pushed to your device."}},
 ]},

 {key:"교육·학습", q:{ja:"テスト",en:"test"}, mails:[
  {f:{ja:"小林 先生",en:"Mr. Kobayashi"},c:P[7],g:"today",t:"16:35",u:false,
   s:{ja:"来週の授業準備の進捗について",en:"Next week's lesson prep — progress"},
   b:{ja:"お疲れさまです、小林です。\n\n来週の授業準備の進捗を共有します。\n・単元: 「二次関数の応用」\n・教材: スライドとワークシートを作成中（8割完了）\n・小テスト: 5問、明日までに確定\n\n資料は明日中に共有フォルダにアップします。習熟度に差があるため、発展問題と基礎問題の2段階で用意しています。気づいた点があればフィードバックください。"+SIG("小林 賢","数学科"),
      en:"Hi, this is Kobayashi.\n\nProgress on next week's lessons.\n・Unit: \"Applications of quadratic functions\"\n・Materials: slides and worksheets in progress (80% done)\n・Quiz: 5 questions, finalized by tomorrow\n\nI'll upload materials to the shared folder tomorrow. Given the range in proficiency, I've prepared two tiers — advanced and basic. Feedback welcome."+SIGe("Ken Kobayashi","Math Dept.")}},
  {f:{ja:"教務部",en:"Academic Office"},c:P[0],g:"today",t:"15:15",u:true,
   s:{ja:"Re: 金曜の時間割変更について",en:"Re: Friday timetable change"},
   b:{ja:"先生各位\n\nご相談いただいた件、金曜の時間割を一部変更しました。\n・3限と5限を入れ替え（体育館工事のため）\n・変更対象: 2年A〜C組\n・反映日: 6/27(金)から\n\n生徒への周知は担任からお願いします。掲示とアプリ配信は教務で対応済みです。ご不便をおかけしますがよろしくお願いします。\n\n> 小林先生:\n> 金曜3限を移動できないか相談です。"+SIG("教務部","時間割担当"),
      en:"To teachers,\n\nRegarding your request, we've adjusted Friday's timetable.\n・Swap periods 3 and 5 (gym construction)\n・Affected: Grade 2, classes A–C\n・Effective: Fri Jun 27\n\nHomeroom teachers, please inform students. The office has handled postings and the app push. Thanks for bearing with us.\n\n> Mr. Kobayashi wrote:\n> Could we move Friday's 3rd period?"+SIGe("Academic Office","Timetable")}},
  {f:{ja:"印刷室",en:"Print Room"},c:P[4],g:"today",t:"14:00",u:false,
   s:{ja:"プリント印刷完了のお知らせ（40部）",en:"Handout printing complete (40 copies)"},
   b:{ja:"ご依頼いただいた印刷が完了しました。\n\n・内容: 数学ワークシート（両面・A4）\n・部数: 40部\n・仕上げ: ホチキス左上留め\n\n職員室前の受け取り棚（棚番12）に置いています。本日中にお受け取りください。追加が必要な場合はデータを再送いただければ対応します。"+SIG("印刷室","事務"),
      en:"Your print job is complete.\n\n・Content: math worksheet (double-sided, A4)\n・Copies: 40\n・Finishing: stapled top-left\n\nThey're on the pickup shelf (No. 12) by the staff room. Please collect today. For more copies, resend the file and we'll handle it."+SIGe("Print Room","Office")}},
  {f:{ja:"佐藤 先生",en:"Ms. Sato"},c:P[0],g:"yest",t:"18:00",u:false,
   s:{ja:"テスト範囲の確定（第3章まで）",en:"Test scope finalized (through Chapter 3)"},
   b:{ja:"お疲れさまです、佐藤です。\n\n期末テストの範囲を確定しました。\n・範囲: 教科書 第3章まで＋配布プリントNo.1〜4\n・出題比率: 基礎6：応用4\n・実施日: 7/10(木) 2限\n\n生徒には明日のHRで周知します。範囲表は学年掲示板にも貼り出します。作問は7/3までに教務へ提出予定です。"+SIG("佐藤 玲","理科"),
      en:"Hi, this is Sato.\n\nThe final-exam scope is set.\n・Scope: textbook through Ch. 3 + handouts No. 1–4\n・Weighting: basics 6 : applied 4\n・Date: Thu Jul 10, 2nd period\n\nI'll tell students at tomorrow's homeroom and post the scope on the grade board. Questions will be submitted to the office by Jul 3."+SIGe("Rei Sato","Science")}},
  {f:{ja:"保護者会 事務",en:"PTA Office"},c:P[9],g:"yest",t:"12:00",u:false,
   s:{ja:"個人面談の日程調整のお願い",en:"Please help schedule parent meetings"},
   b:{ja:"先生方へ\n\n7月の個人面談の日程調整を開始します。\n・期間: 7/14(月)〜7/18(金)\n・1枠: 15分　・1日あたり最大8枠\n・方法: 保護者はアプリの予約フォームから選択\n\n各クラスの空き時間を6/30までに教務へご提出ください。オンライン面談希望の保護者も一定数見込まれます。調整のほどよろしくお願いします。"+SIG("保護者会 事務局","PTA"),
      en:"To teachers,\n\nWe're starting July's parent-meeting scheduling.\n・Period: Mon Jul 14 – Fri Jul 18\n・Slot: 15 min　・Max 8 slots/day\n・Method: parents book via the app form\n\nPlease submit each class's availability to the office by Jun 30. Some parents will request online meetings. Thanks for coordinating."+SIGe("PTA Office","PTA")}},
  {f:{ja:"田中 先生",en:"Mr. Tanaka"},c:P[1],g:"yest",t:"10:30",u:false,
   s:{ja:"お便り(学年通信)の下書きを作成中です",en:"Drafting the grade newsletter"},
   b:{ja:"お疲れさまです、田中です。\n\n今月の学年通信の下書きを作成中です。\n・内容: 期末テストの案内、面談日程、夏休みの過ごし方\n・写真: 先日の校外学習を2点掲載予定\n\n夕方までに下書きを共有しますので、内容のご確認をお願いします。特に日程の記載に誤りがないか、複数の目で見ていただけると助かります。"+SIG("田中 亮","2年主任"),
      en:"Hi, this is Tanaka.\n\nI'm drafting this month's grade newsletter.\n・Content: exam info, meeting schedule, tips for summer break\n・Photos: two from the recent field trip\n\nI'll share the draft by this evening — please review. It would help to have several eyes on the dates in particular."+SIGe("Ryo Tanaka","Grade 2 Lead")}},
  {f:{ja:"教務部",en:"Academic Office"},c:P[0],g:"today",t:"17:02",u:true,in:true,
   s:{ja:"Re: 来月の研究授業のご案内（指導案提出）",en:"Re: Next month's open class (submit lesson plan)"},
   p:{ja:"研究授業の日程が決まりました。指導案の提出をお願いします。",en:"The open-class date is set. Please submit your lesson plan."},
   b:{ja:"先生各位\n\n来月の研究授業の日程が決まりました。\n・日時: 7/16(水) 5限\n・授業者: 小林先生（数学）\n・参観: 全教員＋指導主事1名\n\nつきましては、授業者は指導案を7/9までに教務へご提出ください。参観される先生は当日の授業を自習等に振り替えるようご調整をお願いします。事後の研究協議は放課後15:45からです。"+SIG("教務部","研究推進担当"),
      en:"To teachers,\n\nNext month's open class is scheduled.\n・When: Wed Jul 16, 5th period\n・Teacher: Mr. Kobayashi (Math)\n・Observers: all teachers + 1 supervisor\n\nThe presenting teacher should submit the lesson plan to the office by Jul 9. Observers, please arrange self-study for your classes that period. The post-class discussion is at 15:45."+SIGe("Academic Office","Curriculum")}},
  {f:{ja:"高橋 先生",en:"Ms. Takahashi"},c:P[3],g:"today",t:"17:06",u:true,in:true,
   s:{ja:"補習の希望者リストをまとめました",en:"Compiled the supplementary-lesson list"},
   b:{ja:"お疲れさまです、高橋です。\n\n夏期補習の希望者リストをまとめました。\n・数学: 18名　・英語: 14名　・理科: 9名\n・希望時間帯: 午前が最多\n\n人数の多い数学は2クラス編成が必要かもしれません。担当割りについてご相談させてください。詳細リストは共有フォルダ（補習2026）に置いています。ご確認お願いします。"+SIG("高橋 恵","進路指導"),
      en:"Hi, this is Takahashi.\n\nI've compiled the summer supplementary-lesson list.\n・Math: 18　・English: 14　・Science: 9\n・Preferred time: mornings most popular\n\nMath may need two classes given the numbers. Let's discuss assignments. The full list is in the shared folder (Supplementary 2026). Please review."+SIGe("Megumi Takahashi","Guidance")}},
 ]},

 {key:"영업·마케팅", q:{ja:"キャンペーン",en:"campaign"}, mails:[
  {f:{ja:"山田 リーダー",en:"Lead Yamada"},c:P[8],g:"today",t:"16:40",u:false,
   s:{ja:"来月のキャンペーン案（ご確認ください）",en:"Next month's campaign plan (please review)"},
   b:{ja:"お疲れさまです、山田です。\n\n来月のキャンペーン案をまとめました。ご確認をお願いします。\n・テーマ: 「夏の新規獲得」\n・チャネル: Web広告、メール、SNS\n・目標: 新規リード800件（CPA 3,000円以内）\n・期間: 7/1〜7/31\n\n予算配分と主要KPIは添付資料にまとめています。明日のMTGで最終確認し、承認後すぐに広告入稿できる体制です。"+SIG("山田 亮","営業企画チーム"),
      en:"Hi, this is Yamada.\n\nI've put together next month's campaign plan — please review.\n・Theme: \"Summer new-customer acquisition\"\n・Channels: web ads, email, SNS\n・Goal: 800 new leads (CPA under ¥3,000)\n・Period: Jul 1–31\n\nBudget allocation and key KPIs are in the attachment. We'll finalize at tomorrow's meeting and can submit ad creatives right after approval."+SIGe("Ryo Yamada","Sales Planning")}},
  {f:{ja:"マーケ部",en:"Marketing Dept."},c:P[0],g:"today",t:"15:35",u:true,
   s:{ja:"Re: 提案資料のドラフト（先方向け）",en:"Re: Client proposal draft"},
   b:{ja:"山田さん\n\n先方（A社）向けの提案資料のドラフトができました。\n・構成: 課題整理→施策→体制→費用→スケジュール\n・差別化: 導入後3ヶ月の伴走支援を前面に\n・見積: 3プラン提示（松竹梅）\n\n数字の裏付けページだけまだ精査中です。明日のMTGで内容を詰めて、金曜には先方へ提出したいです。フィードバックお願いします。\n\n> 山田さん:\n> A社の提案、いつもの構成でドラフトお願いできますか。"+SIG("鈴木 彩","マーケティング部"),
      en:"Hi Yamada,\n\nThe draft proposal for the client (Company A) is ready.\n・Structure: issues → actions → team → cost → schedule\n・Differentiator: 3-month hands-on support up front\n・Quote: three plans (good/better/best)\n\nOnly the data-backing page still needs review. Let's refine it at tomorrow's meeting and submit to the client Friday. Feedback welcome.\n\n> Yamada wrote:\n> Could you draft the Company A proposal in our usual format?"+SIGe("Aya Suzuki","Marketing Dept.")}},
  {f:{ja:"CRM 通知",en:"CRM Alert"},c:P[4],g:"today",t:"14:20",u:false,
   s:{ja:"【自動】商談リマインド：明日10時 A社",en:"[Auto] Deal reminder: Company A, 10 AM tomorrow"},
   b:{ja:"商談のリマインドです。\n\n● 相手: 株式会社A社（先方3名）\n● 日時: 明日 10:00〜11:00\n● 場所: 先方本社 / オンライン併用\n● 商談フェーズ: 提案（受注確度 60%）\n● 前回メモ: 価格と導入時期がネック。競合B社と比較検討中。\n\n提案資料と見積書の最終版を前日までに準備してください。関連する過去のやり取りはCRMの商談カードから確認できます。",
      en:"A deal reminder.\n\n● Client: Company A (3 attendees)\n● When: tomorrow 10:00–11:00\n● Where: their HQ / hybrid\n● Stage: proposal (win probability 60%)\n● Last note: price and timing are sticking points; comparing with competitor B.\n\nHave the final proposal and quote ready by the day before. Past correspondence is on the CRM deal card."}},
  {f:{ja:"佐藤 マネージャー",en:"Manager Sato"},c:P[0],g:"yest",t:"19:00",u:false,
   s:{ja:"先月の営業実績レポート（前年比120%）",en:"Last month's sales report (120% YoY)"},
   b:{ja:"お疲れさまです、佐藤です。\n\n先月の営業実績レポートを共有します。\n・売上: 前年同月比 120%（目標比 108%）\n・新規獲得: 42社　・失注: 9社（主因は価格）\n・MVP: 山田チーム(達成率131%)\n\n好調の要因はリピート受注の増加です。一方、価格を理由とした失注が増えているため、来月は価値訴求の強化が課題です。詳細は添付をご確認ください。"+SIG("佐藤 誠","営業部 マネージャー"),
      en:"Hi, this is Sato.\n\nSharing last month's sales report.\n・Revenue: 120% YoY (108% of target)\n・New wins: 42　・Losses: 9 (mainly price)\n・MVP: Yamada's team (131% attainment)\n\nRepeat orders drove the strong results. However, price-based losses are rising, so next month's focus is stronger value messaging. See the attachment for details."+SIGe("Makoto Sato","Sales Manager")}},
  {f:{ja:"田中 インサイド",en:"Tanaka (Inside)"},c:P[1],g:"yest",t:"13:10",u:false,
   s:{ja:"ターゲット顧客リストを更新しました",en:"Updated the target customer list"},
   b:{ja:"お疲れさまです、田中です。\n\n来月キャンペーンのターゲット顧客リストを更新しました。\n・抽出条件: 30代・既存顧客・直近6ヶ月未購入\n・件数: 1,240件\n・セグメント: 休眠(A)/優良離反(B)/クロスセル候補(C)\n\nセグメント別に訴求を変える想定です。メール配信の除外リスト（配信停止）も反映済みです。名寄せ後の最終件数は明日確定します。"+SIG("田中 彩花","インサイドセールス"),
      en:"Hi, this is Tanaka.\n\nI've updated the target list for next month's campaign.\n・Criteria: 30s, existing customers, no purchase in 6 months\n・Count: 1,240\n・Segments: dormant (A) / lapsed-VIP (B) / cross-sell (C)\n\nWe'll tailor messaging by segment. The email suppression (opt-out) list is applied. The final de-duplicated count will be set tomorrow."+SIGe("Ayaka Tanaka","Inside Sales")}},
  {f:{ja:"経理部",en:"Finance Dept."},c:P[9],g:"yest",t:"10:00",u:false,
   s:{ja:"【リマインド】今月の経費精算は明日締切",en:"[Reminder] Expense reports due tomorrow"},
   b:{ja:"社員各位\n\n今月分の経費精算の締切が明日(6/25)に迫っています。\n・対象: 6/1〜6/30利用分\n・方法: 経費システムから申請、領収書は画像添付\n・注意: 交通費は経路情報の入力が必須\n\n締切を過ぎると翌月払いになります。承認者の確認時間も考慮し、本日中の申請にご協力ください。ご不明点は経理まで。"+SIG("経理部","精算担当"),
      en:"To all employees,\n\nThis month's expense-report deadline is tomorrow (Jun 25).\n・Covers: usage Jun 1–30\n・How: submit in the expense system, attach receipt images\n・Note: transport requires route details\n\nLate submissions roll to next month's payout. Allowing for approver time, please submit today. Questions to Finance."+SIGe("Finance Dept.","Reimbursement")}},
  {f:{ja:"高橋 部長",en:"Director Takahashi"},c:P[3],g:"today",t:"17:02",u:true,in:true,
   s:{ja:"Re:Re: キャンペーン予算配分の確認",en:"Re:Re: Campaign budget allocation"},
   p:{ja:"予算感の共有をお願いします。承認前に配分を確認したいです。",en:"Please share the budget breakdown before I approve."},
   b:{ja:"山田さん、お疲れさまです。\n\n来月キャンペーンの件、承認の前に予算配分だけ確認させてください。\n提案では総額300万との認識ですが、チャネル別の内訳（Web広告/メール/制作費）を教えてもらえますか。\nCPA目標3,000円に対し、Web広告の比率が高い場合はクリエイティブのABテスト費用も見ておきたいです。\n\n数字が固まれば、明日のMTGで最終承認します。\n\n> 山田さん:\n> 予算は前年並みで確保しています。\n>> 高橋部長:\n>> 来月の予算感を早めに共有してください。"+SIG("高橋 剛","マーケティング本部長"),
      en:"Hi Yamada,\n\nBefore I approve next month's campaign, let me just confirm the budget split.\nI understand the proposal is ¥3M total — could you share the by-channel breakdown (web ads / email / production)?\nGiven the ¥3,000 CPA target, if web ads take a large share, I'd like to budget for creative A/B testing too.\n\nOnce the numbers are set, I'll give final approval at tomorrow's meeting.\n\n> Yamada wrote:\n> Budget is secured at last year's level.\n>> Director Takahashi wrote:\n>> Please share next month's budget outlook early."+SIGe("Tsuyoshi Takahashi","Head of Marketing")}},
  {f:{ja:"マーケ部",en:"Marketing Dept."},c:P[0],g:"today",t:"17:06",u:true,in:true,
   s:{ja:"広告クリエイティブ完成（ご確認ください）",en:"Ad creative ready (please review)"},
   b:{ja:"営業企画各位\n\n来月キャンペーンの広告バナーが完成しました。\n・サイズ: 4種（SNS正方形、ストーリー、ディスプレイ横長、メールヘッダー）\n・訴求: 「今なら初月無料」を主軸\n・A/B: メインコピー2案を用意\n\n共有フォルダ（creative_07）に格納しています。文言・表現に薬機/景表法上の懸念がないか、明日までにご確認ください。問題なければ入稿します。"+SIG("マーケティング部","クリエイティブ"),
      en:"To sales planning,\n\nThe ad banners for next month's campaign are ready.\n・Sizes: 4 (SNS square, story, display banner, email header)\n・Message: centered on \"first month free\"\n・A/B: two main-copy variants\n\nStored in the shared folder (creative_07). Please check by tomorrow for any advertising-law/claims concerns. If all's fine, we'll submit them."+SIGe("Marketing Dept.","Creative")}},
 ]},
];

const NOISE=[
 {f:{ja:"HBR",en:"HBR"},c:P[1],g:"today",t:"10:25",u:true,
  s:{ja:"【広告】現役講師が教える 実践AI活用法",en:"[Ad] Practical AI methods from active instructors"},
  p:{ja:"満足度9.7点。非IT職をスマートワーカーに変えるAI応用法。",en:"Rated 9.7. Turn non-IT staff into smart workers with AI."},
  b:{ja:"《PR》\n\n「AIツールは入れたけれど、現場が使いこなせない」——そんな課題を解決する実践講座のご案内です。\n\n・対象: 非IT部門のマネージャー／担当者\n・内容: 資料作成・議事録・メール返信をAIで自動化する具体手順\n・受講者満足度: 9.7 / 10（累計3,200名）\n・特典: テンプレート集（30種）プレゼント\n\n次回開催は7月中旬、オンライン開催です。下記より詳細をご確認ください。\n\n配信停止をご希望の場合はこちら。",
     en:"[PR]\n\n\"We adopted AI tools, but the team can't use them.\" This hands-on course solves exactly that.\n\n・For: managers/staff in non-IT departments\n・Content: concrete steps to automate docs, minutes, and email replies with AI\n・Satisfaction: 9.7 / 10 (3,200 attendees)\n・Bonus: 30 templates included\n\nNext session mid-July, online. See details below.\n\nClick here to unsubscribe."}},
 {f:{ja:"AI Festa 事務局",en:"AI Festa"},c:P[8],g:"today",t:"10:16",u:true,att:true,
  s:{ja:"[AI Festa 26] 出展参加のご案内（1次締切 6/26）",en:"[AI Festa 26] Exhibition invitation (1st deadline Jun 26)"},
  p:{ja:"成功するビジネスのためのAI Festa 26、出展受付中です。",en:"AI Festa 26 for successful business — now accepting exhibitors."},
  b:{ja:"AI Festa 26 出展のご案内\n\n国内最大級のAIビジネス展示会「AI Festa 26」への出展をご案内します。\n・会期: 2026年9月10日〜12日\n・会場: 幕張メッセ\n・来場見込: 25,000名（前回比+20%）\n・1次締切: 6/26（早期割引 15%OFF）\n\n出展要項と申込書を添付しました。ブース区画は先着順です。ご検討ください。",
     en:"AI Festa 26 exhibition invitation\n\nWe invite you to exhibit at \"AI Festa 26,\" one of Japan's largest AI business expos.\n・Dates: Sep 10–12, 2026\n・Venue: Makuhari Messe\n・Expected visitors: 25,000 (+20%)\n・1st deadline: Jun 26 (15% early discount)\n\nThe prospectus and application are attached. Booths are first-come. Please consider."}},
 {f:{ja:"株式会社クオリティア",en:"Qualitia Inc."},c:P[4],g:"today",t:"10:07",u:false,
  s:{ja:"ファミマも導入したBIMIとは？メールの安全を可視化",en:"What is BIMI? Make email safety visible"},
  p:{ja:"ロゴ表示でなりすまし対策。導入メリットを解説します。",en:"Stop spoofing with logo display — benefits explained."},
  b:{ja:"いつもお世話になっております、クオリティアです。\n\n受信トレイに自社ロゴを表示できる「BIMI」が注目されています。\n・なりすましメール対策になる\n・開封率の向上が期待できる\n・ブランド信頼性の訴求\n\n大手企業の導入事例（ファミリーマート様ほか）を交えたホワイトペーパーを無料配布中です。下記からダウンロードいただけます。",
     en:"Thank you for your continued interest — Qualitia.\n\n\"BIMI,\" which displays your logo in the inbox, is drawing attention.\n・Counters spoofing\n・Can improve open rates\n・Reinforces brand trust\n\nWe're offering a free white paper with case studies (FamilyMart and others). Download below."}},
 {f:{ja:"Google Maps Platform",en:"Google Maps Platform"},c:P[0],g:"today",t:"10:03",u:false,
  s:{ja:"【登壇】データで変革するスーパー＆ドラッグストアの顧客体験",en:"[Session] Transforming retail CX with data"},
  p:{ja:"小売業界DXカンファレンス、参加登録受付中。",en:"Retail DX conference — registration open."},
  b:{ja:"Google Maps Platform チームです。\n\n小売業界向けDXカンファレンスにて、位置情報データを活用した顧客体験の変革についてセッションを行います。\n・日時: 7/8(火) 14:00〜\n・形式: オンライン（無料）\n・内容: 店舗送客、商圏分析、来店予測の事例\n\n参加登録は下記から。当日はQ&Aの時間も設けています。",
     en:"This is the Google Maps Platform team.\n\nAt an upcoming retail DX conference, we'll present on transforming CX with location data.\n・When: Tue Jul 8, 14:00\n・Format: online (free)\n・Content: foot-traffic, trade-area analysis, visit prediction cases\n\nRegister below. There will be a Q&A."}},
 {f:{ja:"Salesforce",en:"Salesforce"},c:P[2],g:"today",t:"10:01",u:false,
  s:{ja:"[限定席] Agentic 時代が今、始まります | Digital Summit 2026",en:"[Limited] The Agentic era begins | Digital Summit 2026"},
  p:{ja:"Agentic Marketing & Commerce をリードする一日。",en:"A day leading the Agentic Marketing & Commerce era."},
  b:{ja:"Salesforce Digital Summit 2026 へのご招待です。\n\nAIエージェントがビジネスを変える「Agentic」時代の実践知を一日で。\n・日時: 2026年7月16日\n・会場: ザ・プリンス パークタワー東京\n・基調講演、40超のセッション、ネットワーキング\n\n席数に限りがあります。お早めにご登録ください。",
     en:"An invitation to Salesforce Digital Summit 2026.\n\nA full day of practical know-how for the \"Agentic\" era where AI agents transform business.\n・Date: July 16, 2026\n・Venue: The Prince Park Tower Tokyo\n・Keynote, 40+ sessions, networking\n\nSeats are limited — register early."}},
 {f:{ja:"櫻井 くれは",en:"Kureha Sakurai"},c:P[5],g:"today",t:"9:11",u:false,
  s:{ja:"AI検索対策(GEO/LLMO)で何が変わる？動画で解説",en:"What changes with AI search (GEO/LLMO)? A video"},
  p:{ja:"従来のSEOとの違いを約21分の動画で解説します。",en:"A ~21-min video on how it differs from SEO."},
  b:{ja:"いつもお世話になっております、櫻井です。\n\nAIが検索結果を生成する時代、従来のSEOだけでは露出が取れなくなってきています。\n「GEO/LLMO(生成エンジン最適化)」で何をすべきか、約21分の動画にまとめました。\n・AIに引用されるコンテンツの作り方\n・構造化データの重要性\n・よくある失敗例\n\n動画リンクは下記です。ご感想いただけると嬉しいです。",
     en:"Thank you as always — this is Sakurai.\n\nAs AI generates search results, SEO alone no longer secures visibility.\nI've summarized what to do for \"GEO/LLMO\" in a ~21-minute video.\n・How to create content AI cites\n・Why structured data matters\n・Common mistakes\n\nThe video link is below. I'd love your feedback."}},
 {f:{ja:"双日テックイノベーション",en:"Sojitz Tech"},c:P[6],g:"today",t:"8:52",u:false,
  s:{ja:"【製造業必見】計画変更に振り回されない現場づくり",en:"[Manufacturing] Building change-resilient sites"},
  p:{ja:"進捗可視化とデータ活用の進め方をセミナーでご紹介。",en:"A seminar on progress visibility and data use."},
  b:{ja:"製造業のご担当者さまへ\n\n「急な計画変更のたびに現場が混乱する」——多くの工場が抱える課題です。\n本セミナーでは、進捗の可視化とデータ活用で変化に強い現場をつくる方法をご紹介します。\n・日時: 7/9(水) 15:00〜16:00\n・形式: オンライン（無料）\n・事例: 部品メーカーA社の改善事例\n\nお申込みは下記から。",
     en:"To manufacturing professionals,\n\n\"The floor descends into chaos with every sudden plan change\" — a common factory problem.\nThis seminar shows how to build change-resilient sites through progress visibility and data.\n・When: Wed Jul 9, 15:00–16:00\n・Format: online (free)\n・Case: improvement at parts maker A\n\nRegister below."}},
 {f:{ja:"メッセ ミュンヘン",en:"Messe München"},c:P[9],g:"today",t:"8:30",u:false,
  s:{ja:"[productronica 2027] 出展企業募集のご案内",en:"[productronica 2027] Call for exhibitors"},
  p:{ja:"独ミュンヘン 電子製造・SMT設備展示会。",en:"Munich electronics & SMT equipment expo."},
  b:{ja:"productronica 2027 日本事務局です。\n\n世界最大級の電子製造・SMT設備展示会「productronica」の出展企業を募集しています。\n・会期: 2027年11月（独ミュンヘン）\n・来場: 世界80カ国 約42,000名\n・日本企業向けパビリオンもご用意\n\n早期申込特典があります。ご興味があれば資料をお送りします。",
     en:"This is the productronica 2027 Japan office.\n\nWe're recruiting exhibitors for \"productronica,\" one of the world's largest electronics/SMT expos.\n・Dates: Nov 2027 (Munich)\n・Visitors: ~42,000 from 80 countries\n・A Japan pavilion is available\n\nEarly-bird perks apply. We'll send materials on request."}},
 {f:{ja:"flyle マーケ",en:"flyle Marketing"},c:P[3],g:"today",t:"8:04",u:false,
  s:{ja:"【AI時代に見直すSVの役割】残る仕事・新たに求められる役割",en:"[Rethinking the SV role in the AI era]"},
  p:{ja:"AIで再設計するスーパーバイザーの6つの業務。",en:"Six supervisor tasks redesigned with AI."},
  b:{ja:"flyle 事務局です。\n\nAIの普及で、現場を統括するスーパーバイザー(SV)の役割が大きく変わろうとしています。\n本セミナーでは、SVの業務を6つに整理し、AIで再設計する方法を解説します。\n・残る仕事／なくなる仕事の見極め\n・新たに求められるマネジメント\n\n参加無料。アーカイブ配信もあります。下記よりお申込みください。",
     en:"This is the flyle team.\n\nWith AI's spread, the role of the supervisor (SV) who oversees the floor is changing.\nThis seminar organizes the SV role into six tasks and shows how to redesign them with AI.\n・Which tasks remain vs. disappear\n・New management skills required\n\nFree to attend, with an archive. Register below."}},
 {f:{ja:"Team Tailscale",en:"Team Tailscale"},c:P[7],g:"today",t:"3:16",u:false,
  s:{ja:"Here's your June newsletter from Tailscale",en:"Here's your June newsletter from Tailscale"},
  p:{ja:"Aperture updates, Tailscale Insiders, CFP for Community Day.",en:"Aperture updates, Tailscale Insiders, CFP for Community Day."},
  b:{ja:"Hi there,\n\nTailscale 6月のアップデートをお届けします。\n・Aperture: 新しいアクセス制御が一般提供に\n・Tailscale Insiders: 次回は7月開催\n・Community Day: 登壇者(CFP)を募集中\n\n詳細は各リンクからご覧ください。今月もご利用ありがとうございます。",
     en:"Hi there,\n\nHere are Tailscale's June updates.\n・Aperture: new access controls now GA\n・Tailscale Insiders: next session in July\n・Community Day: CFP for speakers is open\n\nSee the links for details. Thanks for using Tailscale this month."}},
 {f:{ja:"アウトスタンディング",en:"Outstanding"},c:P[1],g:"older",t:"6/23",u:false,
  s:{ja:"投資を受けず顧客に時間を使う｜本日の記事2編",en:"Time on customers, not funding | 2 articles today"},
  p:{ja:"売上1000億の経営者インタビューほか。",en:"A 100B-yen CEO interview and more."},
  b:{ja:"本日のダイジェストをお届けします。\n\n① 「投資を受けず、株主対応の代わりに顧客に時間を使う」——売上1000億企業のトップインタビュー\n② 業界地図で見る、今注目のスタートアップ動向\n\n続きは会員ページでご覧いただけます。",
     en:"Here's today's digest.\n\n① \"No funding — spend time on customers instead of shareholders\": interview with a 100B-yen CEO\n② Startup trends to watch, via the industry map\n\nRead the rest on the members' page."}},
 {f:{ja:"コラボスタイル",en:"Collabo Style"},c:P[0],g:"older",t:"6/23",u:false,
  s:{ja:"【6/25開催】電子決裁後の手入力をゼロに",en:"[Jun 25] Zero manual entry after e-approval"},
  p:{ja:"ワークフロー実践活用法のご紹介ウェビナー。",en:"A webinar on practical workflow tips."},
  b:{ja:"コラボスタイルです。\n\n「決裁は電子化したのに、その後の基幹システムへの手入力が残っている」——そんな“決裁のその先”の無駄をゼロにする方法をご紹介します。\n・日時: 6/25(水) 11:00〜\n・内容: ワークフローと外部連携の実践活用\n\n参加無料です。お申込みは下記から。",
     en:"This is Collabo Style.\n\n\"We digitized approvals, but manual entry into core systems remains.\" We'll show how to eliminate that \"after-approval\" waste.\n・When: Wed Jun 25, 11:00\n・Content: practical workflow and integrations\n\nFree to attend. Register below."}},
 {f:{ja:"STAY24",en:"STAY24"},c:P[4],g:"older",t:"6/23",u:false,
  s:{ja:"タンブラー専門企業 STAY24｜夏のノベルティに",en:"Tumbler specialist STAY24 | for summer novelties"},
  p:{ja:"名入れタンブラーで販促・ノベルティを。",en:"Custom-printed tumblers for promotions."},
  b:{ja:"STAY24 です。\n\n夏の販促・記念品に、名入れタンブラーはいかがでしょうか。\n・小ロット(50個)から対応\n・フルカラー印刷可\n・最短10営業日で納品\n\nサンプル請求・お見積もりは無料です。カタログを添付希望の場合はご返信ください。",
     en:"This is STAY24.\n\nHow about custom-printed tumblers for summer promotions and gifts?\n・From small lots (50)\n・Full-color printing\n・Delivery in as fast as 10 business days\n\nSamples and quotes are free. Reply if you'd like the catalog."}},
 {f:{ja:"サイボウズ kintone",en:"Cybozu kintone"},c:P[2],g:"older",t:"6/23",u:false,
  s:{ja:"ITツールの導入を拒む現場｜kintoneなら浸透させられる？",en:"Sites that resist IT tools | Can kintone stick?"},
  p:{ja:"現場に定着させる導入のコツを事例で解説。",en:"Adoption tips explained with cases."},
  b:{ja:"kintone チームです。\n\n「便利なはずのITツールが、現場に定着しない」。その原因の多くは“作り込みすぎ”と“現場不在”にあります。\n本資料では、現場を巻き込みながら少しずつ広げるkintoneの定着ステップを、3社の事例で解説します。\n\n無料ダウンロードは下記から。",
     en:"This is the kintone team.\n\n\"A supposedly convenient IT tool never sticks on the floor.\" Often the causes are over-engineering and leaving the floor out.\nThis guide explains kintone's step-by-step adoption—bringing the floor along—with three case studies.\n\nFree download below."}},
 {f:{ja:"シェアードIT",en:"SharedIT"},c:P[8],g:"older",t:"6/23",u:false,att:true,
  s:{ja:"広報/マーケ 提案書 2026年下半期版（DL）",en:"PR/Marketing proposal H2 2026 (download)"},
  p:{ja:"商品案内・提案書を更新しました。",en:"Product proposal updated."},
  b:{ja:"いつもお世話になっております、シェアードITです。\n\n2026年下半期の広報/マーケティング商品案内 提案書を更新しました。\n・記事広告メニュー\n・ホワイトペーパー掲載\n・リード獲得プラン\n\n提案書PDFを添付します。媒体資料や価格表もございますので、ご興味があればお気軽にご連絡ください。",
     en:"Thank you for your continued business — SharedIT.\n\nWe've updated our H2 2026 PR/marketing product proposal.\n・Sponsored article menu\n・White-paper placement\n・Lead-gen plans\n\nThe proposal PDF is attached. We also have media kits and price lists—reach out anytime."}},
 {f:{ja:"Notion",en:"Notion"},c:P[9],g:"older",t:"6/22",u:false,
  s:{ja:"新機能のご案内：AIコネクター",en:"New feature: AI Connectors"},
  p:{ja:"Slackやドライブの情報をNotion AIが横断検索。",en:"Notion AI now searches across Slack, Drive, and more."},
  b:{ja:"Notion チームです。\n\n新機能「AIコネクター」をリリースしました。\n・Slack / Google Drive / GitHub などの情報を横断検索\n・Notion AI が外部ツールの内容も参照して回答\n・管理者は接続範囲を制御可能\n\nワークスペースの設定から有効化できます。詳しい使い方はヘルプセンターをご覧ください。",
     en:"This is the Notion team.\n\nWe've released \"AI Connectors.\"\n・Search across Slack / Google Drive / GitHub and more\n・Notion AI answers using external tool content\n・Admins can control connection scope\n\nEnable it in your workspace settings. See the Help Center for details."}},
 {f:{ja:"Zoom",en:"Zoom"},c:P[0],g:"older",t:"6/22",u:true,
  s:{ja:"アカウントのセキュリティ通知：新しい端末からのサインイン",en:"Security notice: sign-in from a new device"},
  p:{ja:"新しい端末からのサインインを検知しました。",en:"We detected a sign-in from a new device."},
  b:{ja:"Zoom アカウントのセキュリティ通知です。\n\n新しい端末からのサインインを検知しました。\n・日時: 6/22 20:14\n・端末: Windows / Chrome\n・場所: 東京(推定)\n\nご本人の操作であれば対応は不要です。心当たりがない場合は、直ちにパスワードを変更し、2要素認証の有効化をおすすめします。",
     en:"A Zoom account security notice.\n\nWe detected a sign-in from a new device.\n・When: Jun 22, 20:14\n・Device: Windows / Chrome\n・Location: Tokyo (estimated)\n\nNo action needed if this was you. If not, change your password immediately and enable two-factor authentication."}},
 {f:{ja:"freee会計",en:"freee"},c:P[4],g:"older",t:"6/22",u:false,att:true,
  s:{ja:"今月の経費レポートが準備できました",en:"Your monthly expense report is ready"},
  p:{ja:"ダウンロードして内容をご確認ください。",en:"Download and review the details."},
  b:{ja:"freee会計です。\n\n今月（6月）の経費レポートが準備できました。\n・経費合計: ¥248,300\n・未承認: 3件\n・要確認: 領収書未添付が1件あります\n\nレポートPDFを添付しています。未承認分の処理と、領収書の添付をお願いします。詳細は管理画面からご確認いただけます。",
     en:"This is freee.\n\nYour monthly (June) expense report is ready.\n・Total expenses: ¥248,300\n・Unapproved: 3\n・Needs attention: 1 item missing a receipt\n\nThe report PDF is attached. Please process the unapproved items and attach the receipt. See the dashboard for details."}},
];

/* 정규화: 모든 메일에 p(미리보기)와 b(본문)를 보장. p 누락 시 본문 첫 줄에서 생성 */
(function(){
  const first=(m,t)=>{
    const lines=((m.b&&m.b[t])||"").split("\n").map(x=>x.trim()).filter(Boolean)
      .map(x=>x.replace(/^《PR》\s*/,"").replace(/^\[PR\]\s*/,""));
    const greet=l=>/(さん|様|各位|皆さま|皆さん|お疲れ様です|お疲れさまです|いつもお世話になっております|先生|師長|ドライバー各位)$|^(Hi|Hello|To\b|Dear|This is)/.test(l)||/[,、]$/.test(l);
    const pick=lines.filter(l=>!greet(l))[0]||lines[0]||"";
    return pick.length>60?pick.slice(0,58)+"…":pick;
  };
  const all=[].concat.apply([],scenarios.map(s=>s.mails)).concat(NOISE);
  all.forEach(m=>{
    if(!m.p) m.p={ja:first(m,"ja"),en:first(m,"en")};
    if(!m.b) m.b={ja:m.p.ja,en:m.p.en};
  });
})();

window.DEMO={P,scenarios,NOISE};
})();
